package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.AdminCustRoom;
import mm.aeon.com.zgen.entity.AdminCustRoomExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AdminCustRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.admin_cust_room
     *
     * @mbg.generated
     */
    long countByExample(AdminCustRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.admin_cust_room
     *
     * @mbg.generated
     */
    int deleteByExample(AdminCustRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.admin_cust_room
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer adCustRoomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.admin_cust_room
     *
     * @mbg.generated
     */
    int insert(AdminCustRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.admin_cust_room
     *
     * @mbg.generated
     */
    int insertSelective(AdminCustRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.admin_cust_room
     *
     * @mbg.generated
     */
    List<AdminCustRoom> selectByExampleWithRowbounds(AdminCustRoomExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.admin_cust_room
     *
     * @mbg.generated
     */
    List<AdminCustRoom> selectByExample(AdminCustRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.admin_cust_room
     *
     * @mbg.generated
     */
    AdminCustRoom selectByPrimaryKey(Integer adCustRoomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.admin_cust_room
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AdminCustRoom record, @Param("example") AdminCustRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.admin_cust_room
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AdminCustRoom record, @Param("example") AdminCustRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.admin_cust_room
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdminCustRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.admin_cust_room
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdminCustRoom record);
}