package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.AgentLevel;
import mm.aeon.com.zgen.entity.AgentLevelExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AgentLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.agent_level
     *
     * @mbg.generated
     */
    long countByExample(AgentLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.agent_level
     *
     * @mbg.generated
     */
    int deleteByExample(AgentLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.agent_level
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer agentLevelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.agent_level
     *
     * @mbg.generated
     */
    int insert(AgentLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.agent_level
     *
     * @mbg.generated
     */
    int insertSelective(AgentLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.agent_level
     *
     * @mbg.generated
     */
    List<AgentLevel> selectByExampleWithRowbounds(AgentLevelExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.agent_level
     *
     * @mbg.generated
     */
    List<AgentLevel> selectByExample(AgentLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.agent_level
     *
     * @mbg.generated
     */
    AgentLevel selectByPrimaryKey(Integer agentLevelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.agent_level
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AgentLevel record, @Param("example") AgentLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.agent_level
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AgentLevel record, @Param("example") AgentLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.agent_level
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AgentLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.agent_level
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AgentLevel record);
}