package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.AppConfig;
import mm.aeon.com.zgen.entity.AppConfigExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AppConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_config
     *
     * @mbg.generated
     */
    long countByExample(AppConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_config
     *
     * @mbg.generated
     */
    int deleteByExample(AppConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer appConfigId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_config
     *
     * @mbg.generated
     */
    int insert(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_config
     *
     * @mbg.generated
     */
    int insertSelective(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_config
     *
     * @mbg.generated
     */
    List<AppConfig> selectByExampleWithRowbounds(AppConfigExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_config
     *
     * @mbg.generated
     */
    List<AppConfig> selectByExample(AppConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_config
     *
     * @mbg.generated
     */
    AppConfig selectByPrimaryKey(Integer appConfigId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AppConfig record, @Param("example") AppConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AppConfig record, @Param("example") AppConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AppConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AppConfig record);
}