package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.AppUsageDetail;
import mm.aeon.com.zgen.entity.AppUsageDetailExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AppUsageDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    long countByExample(AppUsageDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    int deleteByExample(AppUsageDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer appUsageDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    int insert(AppUsageDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    int insertSelective(AppUsageDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    List<AppUsageDetail> selectByExampleWithRowbounds(AppUsageDetailExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    List<AppUsageDetail> selectByExample(AppUsageDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    AppUsageDetail selectByPrimaryKey(Integer appUsageDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AppUsageDetail record, @Param("example") AppUsageDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AppUsageDetail record, @Param("example") AppUsageDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AppUsageDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AppUsageDetail record);
}