package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.AtAgentLevel;
import mm.aeon.com.zgen.entity.AtAgentLevelExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AtAgentLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_agent_level
     *
     * @mbg.generated
     */
    long countByExample(AtAgentLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_agent_level
     *
     * @mbg.generated
     */
    int deleteByExample(AtAgentLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_agent_level
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer agentLevelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_agent_level
     *
     * @mbg.generated
     */
    int insert(AtAgentLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_agent_level
     *
     * @mbg.generated
     */
    int insertSelective(AtAgentLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_agent_level
     *
     * @mbg.generated
     */
    List<AtAgentLevel> selectByExampleWithRowbounds(AtAgentLevelExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_agent_level
     *
     * @mbg.generated
     */
    List<AtAgentLevel> selectByExample(AtAgentLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_agent_level
     *
     * @mbg.generated
     */
    AtAgentLevel selectByPrimaryKey(Integer agentLevelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_agent_level
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AtAgentLevel record, @Param("example") AtAgentLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_agent_level
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AtAgentLevel record, @Param("example") AtAgentLevelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_agent_level
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AtAgentLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_agent_level
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AtAgentLevel record);
}