package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.AtScheduleTime;
import mm.aeon.com.zgen.entity.AtScheduleTimeExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AtScheduleTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_schedule_time
     *
     * @mbg.generated
     */
    long countByExample(AtScheduleTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_schedule_time
     *
     * @mbg.generated
     */
    int deleteByExample(AtScheduleTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_schedule_time
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer scheduleTimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_schedule_time
     *
     * @mbg.generated
     */
    int insert(AtScheduleTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_schedule_time
     *
     * @mbg.generated
     */
    int insertSelective(AtScheduleTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_schedule_time
     *
     * @mbg.generated
     */
    List<AtScheduleTime> selectByExampleWithRowbounds(AtScheduleTimeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_schedule_time
     *
     * @mbg.generated
     */
    List<AtScheduleTime> selectByExample(AtScheduleTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_schedule_time
     *
     * @mbg.generated
     */
    AtScheduleTime selectByPrimaryKey(Integer scheduleTimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_schedule_time
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AtScheduleTime record, @Param("example") AtScheduleTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_schedule_time
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AtScheduleTime record, @Param("example") AtScheduleTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_schedule_time
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AtScheduleTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_schedule_time
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AtScheduleTime record);
}