package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.CompanyInfo;
import mm.aeon.com.zgen.entity.CompanyInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CompanyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.company_info
     *
     * @mbg.generated
     */
    long countByExample(CompanyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.company_info
     *
     * @mbg.generated
     */
    int deleteByExample(CompanyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.company_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer companyInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.company_info
     *
     * @mbg.generated
     */
    int insert(CompanyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.company_info
     *
     * @mbg.generated
     */
    int insertSelective(CompanyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.company_info
     *
     * @mbg.generated
     */
    List<CompanyInfo> selectByExampleWithRowbounds(CompanyInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.company_info
     *
     * @mbg.generated
     */
    List<CompanyInfo> selectByExample(CompanyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.company_info
     *
     * @mbg.generated
     */
    CompanyInfo selectByPrimaryKey(Integer companyInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.company_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CompanyInfo record, @Param("example") CompanyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.company_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CompanyInfo record, @Param("example") CompanyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.company_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CompanyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.company_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CompanyInfo record);
}