package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.CouponTemplate;
import mm.aeon.com.zgen.entity.CouponTemplateExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CouponTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_template
     *
     * @mbg.generated
     */
    long countByExample(CouponTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_template
     *
     * @mbg.generated
     */
    int deleteByExample(CouponTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_template
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer couponTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_template
     *
     * @mbg.generated
     */
    int insert(CouponTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_template
     *
     * @mbg.generated
     */
    int insertSelective(CouponTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_template
     *
     * @mbg.generated
     */
    List<CouponTemplate> selectByExampleWithRowbounds(CouponTemplateExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_template
     *
     * @mbg.generated
     */
    List<CouponTemplate> selectByExample(CouponTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_template
     *
     * @mbg.generated
     */
    CouponTemplate selectByPrimaryKey(Integer couponTemplateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_template
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CouponTemplate record, @Param("example") CouponTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_template
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CouponTemplate record, @Param("example") CouponTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CouponTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_template
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CouponTemplate record);
}