package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.CustomerInfoUpdateHistory;
import mm.aeon.com.zgen.entity.CustomerInfoUpdateHistoryExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CustomerInfoUpdateHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.customer_info_update_history
     *
     * @mbg.generated
     */
    long countByExample(CustomerInfoUpdateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.customer_info_update_history
     *
     * @mbg.generated
     */
    int deleteByExample(CustomerInfoUpdateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.customer_info_update_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer customerInfoUpdateHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.customer_info_update_history
     *
     * @mbg.generated
     */
    int insert(CustomerInfoUpdateHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.customer_info_update_history
     *
     * @mbg.generated
     */
    int insertSelective(CustomerInfoUpdateHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.customer_info_update_history
     *
     * @mbg.generated
     */
    List<CustomerInfoUpdateHistory> selectByExampleWithRowbounds(CustomerInfoUpdateHistoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.customer_info_update_history
     *
     * @mbg.generated
     */
    List<CustomerInfoUpdateHistory> selectByExample(CustomerInfoUpdateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.customer_info_update_history
     *
     * @mbg.generated
     */
    CustomerInfoUpdateHistory selectByPrimaryKey(Integer customerInfoUpdateHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.customer_info_update_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CustomerInfoUpdateHistory record, @Param("example") CustomerInfoUpdateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.customer_info_update_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CustomerInfoUpdateHistory record, @Param("example") CustomerInfoUpdateHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.customer_info_update_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustomerInfoUpdateHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.customer_info_update_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustomerInfoUpdateHistory record);
}