package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.CustSecQuestion;
import mm.aeon.com.zgen.entity.CustSecQuestionExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CustSecQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.cust_sec_question
     *
     * @mbg.generated
     */
    long countByExample(CustSecQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.cust_sec_question
     *
     * @mbg.generated
     */
    int deleteByExample(CustSecQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.cust_sec_question
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer custSecQuesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.cust_sec_question
     *
     * @mbg.generated
     */
    int insert(CustSecQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.cust_sec_question
     *
     * @mbg.generated
     */
    int insertSelective(CustSecQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.cust_sec_question
     *
     * @mbg.generated
     */
    List<CustSecQuestion> selectByExampleWithRowbounds(CustSecQuestionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.cust_sec_question
     *
     * @mbg.generated
     */
    List<CustSecQuestion> selectByExample(CustSecQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.cust_sec_question
     *
     * @mbg.generated
     */
    CustSecQuestion selectByPrimaryKey(Integer custSecQuesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.cust_sec_question
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CustSecQuestion record, @Param("example") CustSecQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.cust_sec_question
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CustSecQuestion record, @Param("example") CustSecQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.cust_sec_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CustSecQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.cust_sec_question
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CustSecQuestion record);
}