package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.DaApplicationInfo;
import mm.aeon.com.zgen.entity.DaApplicationInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DaApplicationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info
     *
     * @mbg.generated
     */
    long countByExample(DaApplicationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info
     *
     * @mbg.generated
     */
    int deleteByExample(DaApplicationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer daApplicationInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info
     *
     * @mbg.generated
     */
    int insert(DaApplicationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info
     *
     * @mbg.generated
     */
    int insertSelective(DaApplicationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info
     *
     * @mbg.generated
     */
    List<DaApplicationInfo> selectByExampleWithRowbounds(DaApplicationInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info
     *
     * @mbg.generated
     */
    List<DaApplicationInfo> selectByExample(DaApplicationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info
     *
     * @mbg.generated
     */
    DaApplicationInfo selectByPrimaryKey(Integer daApplicationInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DaApplicationInfo record, @Param("example") DaApplicationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DaApplicationInfo record, @Param("example") DaApplicationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DaApplicationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DaApplicationInfo record);
}