package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.DaApplicationType;
import mm.aeon.com.zgen.entity.DaApplicationTypeExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DaApplicationTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_type
     *
     * @mbg.generated
     */
    long countByExample(DaApplicationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_type
     *
     * @mbg.generated
     */
    int deleteByExample(DaApplicationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer daApplicationTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_type
     *
     * @mbg.generated
     */
    int insert(DaApplicationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_type
     *
     * @mbg.generated
     */
    int insertSelective(DaApplicationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_type
     *
     * @mbg.generated
     */
    List<DaApplicationType> selectByExampleWithRowbounds(DaApplicationTypeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_type
     *
     * @mbg.generated
     */
    List<DaApplicationType> selectByExample(DaApplicationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_type
     *
     * @mbg.generated
     */
    DaApplicationType selectByPrimaryKey(Integer daApplicationTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DaApplicationType record, @Param("example") DaApplicationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DaApplicationType record, @Param("example") DaApplicationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DaApplicationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DaApplicationType record);
}