package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.DaApplicantCompanyInfo;
import mm.aeon.com.zgen.entity.DaApplicantCompanyInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DaApplicantCompanyInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_applicant_company_info
     *
     * @mbg.generated
     */
    long countByExample(DaApplicantCompanyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_applicant_company_info
     *
     * @mbg.generated
     */
    int deleteByExample(DaApplicantCompanyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_applicant_company_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer daApplicantCompanyInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_applicant_company_info
     *
     * @mbg.generated
     */
    int insert(DaApplicantCompanyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_applicant_company_info
     *
     * @mbg.generated
     */
    int insertSelective(DaApplicantCompanyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_applicant_company_info
     *
     * @mbg.generated
     */
    List<DaApplicantCompanyInfo> selectByExampleWithRowbounds(DaApplicantCompanyInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_applicant_company_info
     *
     * @mbg.generated
     */
    List<DaApplicantCompanyInfo> selectByExample(DaApplicantCompanyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_applicant_company_info
     *
     * @mbg.generated
     */
    DaApplicantCompanyInfo selectByPrimaryKey(Integer daApplicantCompanyInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_applicant_company_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DaApplicantCompanyInfo record, @Param("example") DaApplicantCompanyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_applicant_company_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DaApplicantCompanyInfo record, @Param("example") DaApplicantCompanyInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_applicant_company_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DaApplicantCompanyInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_applicant_company_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DaApplicantCompanyInfo record);
}