package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.DaApplicationInfoHistory;
import mm.aeon.com.zgen.entity.DaApplicationInfoHistoryExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DaApplicationInfoHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info_history
     *
     * @mbg.generated
     */
    long countByExample(DaApplicationInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info_history
     *
     * @mbg.generated
     */
    int deleteByExample(DaApplicationInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer daApplicationInfoHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info_history
     *
     * @mbg.generated
     */
    int insert(DaApplicationInfoHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info_history
     *
     * @mbg.generated
     */
    int insertSelective(DaApplicationInfoHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info_history
     *
     * @mbg.generated
     */
    List<DaApplicationInfoHistory> selectByExampleWithRowbounds(DaApplicationInfoHistoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info_history
     *
     * @mbg.generated
     */
    List<DaApplicationInfoHistory> selectByExample(DaApplicationInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info_history
     *
     * @mbg.generated
     */
    DaApplicationInfoHistory selectByPrimaryKey(Integer daApplicationInfoHistoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DaApplicationInfoHistory record, @Param("example") DaApplicationInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DaApplicationInfoHistory record, @Param("example") DaApplicationInfoHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DaApplicationInfoHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_application_info_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DaApplicationInfoHistory record);
}