package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.DaCheckingAttachment;
import mm.aeon.com.zgen.entity.DaCheckingAttachmentExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DaCheckingAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_checking_attachment
     *
     * @mbg.generated
     */
    long countByExample(DaCheckingAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_checking_attachment
     *
     * @mbg.generated
     */
    int deleteByExample(DaCheckingAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_checking_attachment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer daCheckingAttachmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_checking_attachment
     *
     * @mbg.generated
     */
    int insert(DaCheckingAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_checking_attachment
     *
     * @mbg.generated
     */
    int insertSelective(DaCheckingAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_checking_attachment
     *
     * @mbg.generated
     */
    List<DaCheckingAttachment> selectByExampleWithRowbounds(DaCheckingAttachmentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_checking_attachment
     *
     * @mbg.generated
     */
    List<DaCheckingAttachment> selectByExample(DaCheckingAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_checking_attachment
     *
     * @mbg.generated
     */
    DaCheckingAttachment selectByPrimaryKey(Integer daCheckingAttachmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_checking_attachment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DaCheckingAttachment record, @Param("example") DaCheckingAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_checking_attachment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DaCheckingAttachment record, @Param("example") DaCheckingAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_checking_attachment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DaCheckingAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_checking_attachment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DaCheckingAttachment record);
}