package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.DaCityInfo;
import mm.aeon.com.zgen.entity.DaCityInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DaCityInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_city_info
     *
     * @mbg.generated
     */
    long countByExample(DaCityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_city_info
     *
     * @mbg.generated
     */
    int deleteByExample(DaCityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_city_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_city_info
     *
     * @mbg.generated
     */
    int insert(DaCityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_city_info
     *
     * @mbg.generated
     */
    int insertSelective(DaCityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_city_info
     *
     * @mbg.generated
     */
    List<DaCityInfo> selectByExampleWithRowbounds(DaCityInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_city_info
     *
     * @mbg.generated
     */
    List<DaCityInfo> selectByExample(DaCityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_city_info
     *
     * @mbg.generated
     */
    DaCityInfo selectByPrimaryKey(Integer cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_city_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DaCityInfo record, @Param("example") DaCityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_city_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DaCityInfo record, @Param("example") DaCityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_city_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DaCityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_city_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DaCityInfo record);
}