package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.DaCustomerInfoEditReq;
import mm.aeon.com.zgen.entity.DaCustomerInfoEditReqExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DaCustomerInfoEditReqMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_customer_info_edit_req
     *
     * @mbg.generated
     */
    long countByExample(DaCustomerInfoEditReqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_customer_info_edit_req
     *
     * @mbg.generated
     */
    int deleteByExample(DaCustomerInfoEditReqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_customer_info_edit_req
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer daCustomerInfoEditReqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_customer_info_edit_req
     *
     * @mbg.generated
     */
    int insert(DaCustomerInfoEditReq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_customer_info_edit_req
     *
     * @mbg.generated
     */
    int insertSelective(DaCustomerInfoEditReq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_customer_info_edit_req
     *
     * @mbg.generated
     */
    List<DaCustomerInfoEditReq> selectByExampleWithRowbounds(DaCustomerInfoEditReqExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_customer_info_edit_req
     *
     * @mbg.generated
     */
    List<DaCustomerInfoEditReq> selectByExample(DaCustomerInfoEditReqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_customer_info_edit_req
     *
     * @mbg.generated
     */
    DaCustomerInfoEditReq selectByPrimaryKey(Integer daCustomerInfoEditReqId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_customer_info_edit_req
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DaCustomerInfoEditReq record, @Param("example") DaCustomerInfoEditReqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_customer_info_edit_req
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DaCustomerInfoEditReq record, @Param("example") DaCustomerInfoEditReqExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_customer_info_edit_req
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DaCustomerInfoEditReq record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_customer_info_edit_req
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DaCustomerInfoEditReq record);
}