package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.DaDepartmentInfo;
import mm.aeon.com.zgen.entity.DaDepartmentInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DaDepartmentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_department_info
     *
     * @mbg.generated
     */
    long countByExample(DaDepartmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_department_info
     *
     * @mbg.generated
     */
    int deleteByExample(DaDepartmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_department_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer daDepartmentInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_department_info
     *
     * @mbg.generated
     */
    int insert(DaDepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_department_info
     *
     * @mbg.generated
     */
    int insertSelective(DaDepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_department_info
     *
     * @mbg.generated
     */
    List<DaDepartmentInfo> selectByExampleWithRowbounds(DaDepartmentInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_department_info
     *
     * @mbg.generated
     */
    List<DaDepartmentInfo> selectByExample(DaDepartmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_department_info
     *
     * @mbg.generated
     */
    DaDepartmentInfo selectByPrimaryKey(Integer daDepartmentInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_department_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DaDepartmentInfo record, @Param("example") DaDepartmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_department_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DaDepartmentInfo record, @Param("example") DaDepartmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_department_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DaDepartmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_department_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DaDepartmentInfo record);
}