package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.DaGuarantorInfo;
import mm.aeon.com.zgen.entity.DaGuarantorInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DaGuarantorInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_guarantor_info
     *
     * @mbg.generated
     */
    long countByExample(DaGuarantorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_guarantor_info
     *
     * @mbg.generated
     */
    int deleteByExample(DaGuarantorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_guarantor_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer daGuarantorInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_guarantor_info
     *
     * @mbg.generated
     */
    int insert(DaGuarantorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_guarantor_info
     *
     * @mbg.generated
     */
    int insertSelective(DaGuarantorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_guarantor_info
     *
     * @mbg.generated
     */
    List<DaGuarantorInfo> selectByExampleWithRowbounds(DaGuarantorInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_guarantor_info
     *
     * @mbg.generated
     */
    List<DaGuarantorInfo> selectByExample(DaGuarantorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_guarantor_info
     *
     * @mbg.generated
     */
    DaGuarantorInfo selectByPrimaryKey(Integer daGuarantorInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_guarantor_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DaGuarantorInfo record, @Param("example") DaGuarantorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_guarantor_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DaGuarantorInfo record, @Param("example") DaGuarantorInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_guarantor_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DaGuarantorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_guarantor_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DaGuarantorInfo record);
}