package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.DaInterestInfo;
import mm.aeon.com.zgen.entity.DaInterestInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DaInterestInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_interest_info
     *
     * @mbg.generated
     */
    long countByExample(DaInterestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_interest_info
     *
     * @mbg.generated
     */
    int deleteByExample(DaInterestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_interest_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer daInterestInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_interest_info
     *
     * @mbg.generated
     */
    int insert(DaInterestInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_interest_info
     *
     * @mbg.generated
     */
    int insertSelective(DaInterestInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_interest_info
     *
     * @mbg.generated
     */
    List<DaInterestInfo> selectByExampleWithRowbounds(DaInterestInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_interest_info
     *
     * @mbg.generated
     */
    List<DaInterestInfo> selectByExample(DaInterestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_interest_info
     *
     * @mbg.generated
     */
    DaInterestInfo selectByPrimaryKey(Integer daInterestInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_interest_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DaInterestInfo record, @Param("example") DaInterestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_interest_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DaInterestInfo record, @Param("example") DaInterestInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_interest_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DaInterestInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_interest_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DaInterestInfo record);
}