package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.DaItemLabel;
import mm.aeon.com.zgen.entity.DaItemLabelExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DaItemLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_item_label
     *
     * @mbg.generated
     */
    long countByExample(DaItemLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_item_label
     *
     * @mbg.generated
     */
    int deleteByExample(DaItemLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_item_label
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer daItemLabelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_item_label
     *
     * @mbg.generated
     */
    int insert(DaItemLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_item_label
     *
     * @mbg.generated
     */
    int insertSelective(DaItemLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_item_label
     *
     * @mbg.generated
     */
    List<DaItemLabel> selectByExampleWithRowbounds(DaItemLabelExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_item_label
     *
     * @mbg.generated
     */
    List<DaItemLabel> selectByExample(DaItemLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_item_label
     *
     * @mbg.generated
     */
    DaItemLabel selectByPrimaryKey(Integer daItemLabelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_item_label
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DaItemLabel record, @Param("example") DaItemLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_item_label
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DaItemLabel record, @Param("example") DaItemLabelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_item_label
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DaItemLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_item_label
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DaItemLabel record);
}