package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.DaOperatorRole;
import mm.aeon.com.zgen.entity.DaOperatorRoleExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DaOperatorRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_operator_role
     *
     * @mbg.generated
     */
    long countByExample(DaOperatorRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_operator_role
     *
     * @mbg.generated
     */
    int deleteByExample(DaOperatorRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_operator_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer daOperatorRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_operator_role
     *
     * @mbg.generated
     */
    int insert(DaOperatorRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_operator_role
     *
     * @mbg.generated
     */
    int insertSelective(DaOperatorRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_operator_role
     *
     * @mbg.generated
     */
    List<DaOperatorRole> selectByExampleWithRowbounds(DaOperatorRoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_operator_role
     *
     * @mbg.generated
     */
    List<DaOperatorRole> selectByExample(DaOperatorRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_operator_role
     *
     * @mbg.generated
     */
    DaOperatorRole selectByPrimaryKey(Integer daOperatorRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_operator_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DaOperatorRole record, @Param("example") DaOperatorRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_operator_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DaOperatorRole record, @Param("example") DaOperatorRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_operator_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DaOperatorRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_operator_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DaOperatorRole record);
}