package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.DaPurchaseInfo;
import mm.aeon.com.zgen.entity.DaPurchaseInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DaPurchaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info
     *
     * @mbg.generated
     */
    long countByExample(DaPurchaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info
     *
     * @mbg.generated
     */
    int deleteByExample(DaPurchaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer daPurchaseInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info
     *
     * @mbg.generated
     */
    int insert(DaPurchaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info
     *
     * @mbg.generated
     */
    int insertSelective(DaPurchaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info
     *
     * @mbg.generated
     */
    List<DaPurchaseInfo> selectByExampleWithRowbounds(DaPurchaseInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info
     *
     * @mbg.generated
     */
    List<DaPurchaseInfo> selectByExample(DaPurchaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info
     *
     * @mbg.generated
     */
    DaPurchaseInfo selectByPrimaryKey(Integer daPurchaseInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DaPurchaseInfo record, @Param("example") DaPurchaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DaPurchaseInfo record, @Param("example") DaPurchaseInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DaPurchaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DaPurchaseInfo record);
}