package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.DaPurchaseInfoProduct;
import mm.aeon.com.zgen.entity.DaPurchaseInfoProductExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DaPurchaseInfoProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info_product
     *
     * @mbg.generated
     */
    long countByExample(DaPurchaseInfoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info_product
     *
     * @mbg.generated
     */
    int deleteByExample(DaPurchaseInfoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info_product
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer daPurchaseInfoProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info_product
     *
     * @mbg.generated
     */
    int insert(DaPurchaseInfoProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info_product
     *
     * @mbg.generated
     */
    int insertSelective(DaPurchaseInfoProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info_product
     *
     * @mbg.generated
     */
    List<DaPurchaseInfoProduct> selectByExampleWithRowbounds(DaPurchaseInfoProductExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info_product
     *
     * @mbg.generated
     */
    List<DaPurchaseInfoProduct> selectByExample(DaPurchaseInfoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info_product
     *
     * @mbg.generated
     */
    DaPurchaseInfoProduct selectByPrimaryKey(Integer daPurchaseInfoProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info_product
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DaPurchaseInfoProduct record, @Param("example") DaPurchaseInfoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info_product
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DaPurchaseInfoProduct record, @Param("example") DaPurchaseInfoProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DaPurchaseInfoProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info_product
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DaPurchaseInfoProduct record);
}