package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.DaUserDepartment;
import mm.aeon.com.zgen.entity.DaUserDepartmentExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DaUserDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_user_department
     *
     * @mbg.generated
     */
    long countByExample(DaUserDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_user_department
     *
     * @mbg.generated
     */
    int deleteByExample(DaUserDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_user_department
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer daUserDepartmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_user_department
     *
     * @mbg.generated
     */
    int insert(DaUserDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_user_department
     *
     * @mbg.generated
     */
    int insertSelective(DaUserDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_user_department
     *
     * @mbg.generated
     */
    List<DaUserDepartment> selectByExampleWithRowbounds(DaUserDepartmentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_user_department
     *
     * @mbg.generated
     */
    List<DaUserDepartment> selectByExample(DaUserDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_user_department
     *
     * @mbg.generated
     */
    DaUserDepartment selectByPrimaryKey(Integer daUserDepartmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_user_department
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DaUserDepartment record, @Param("example") DaUserDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_user_department
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DaUserDepartment record, @Param("example") DaUserDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_user_department
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DaUserDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_user_department
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DaUserDepartment record);
}