package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.EventType;
import mm.aeon.com.zgen.entity.EventTypeExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EventTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_type
     *
     * @mbg.generated
     */
    long countByExample(EventTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_type
     *
     * @mbg.generated
     */
    int deleteByExample(EventTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer eventTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_type
     *
     * @mbg.generated
     */
    int insert(EventType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_type
     *
     * @mbg.generated
     */
    int insertSelective(EventType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_type
     *
     * @mbg.generated
     */
    List<EventType> selectByExampleWithRowbounds(EventTypeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_type
     *
     * @mbg.generated
     */
    List<EventType> selectByExample(EventTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_type
     *
     * @mbg.generated
     */
    EventType selectByPrimaryKey(Integer eventTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EventType record, @Param("example") EventTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EventType record, @Param("example") EventTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EventType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EventType record);
}