package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.EventInfo;
import mm.aeon.com.zgen.entity.EventInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface EventInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_info
     *
     * @mbg.generated
     */
    long countByExample(EventInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_info
     *
     * @mbg.generated
     */
    int deleteByExample(EventInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_info
     *
     * @mbg.generated
     */
    int insert(EventInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_info
     *
     * @mbg.generated
     */
    int insertSelective(EventInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_info
     *
     * @mbg.generated
     */
    List<EventInfo> selectByExampleWithRowbounds(EventInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_info
     *
     * @mbg.generated
     */
    List<EventInfo> selectByExample(EventInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_info
     *
     * @mbg.generated
     */
    EventInfo selectByPrimaryKey(Integer eventId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") EventInfo record, @Param("example") EventInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") EventInfo record, @Param("example") EventInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EventInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.event_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EventInfo record);
}