package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.FreeMessageInfo;
import mm.aeon.com.zgen.entity.FreeMessageInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FreeMessageInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_info
     *
     * @mbg.generated
     */
    long countByExample(FreeMessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_info
     *
     * @mbg.generated
     */
    int deleteByExample(FreeMessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer freeMessageInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_info
     *
     * @mbg.generated
     */
    int insert(FreeMessageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_info
     *
     * @mbg.generated
     */
    int insertSelective(FreeMessageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_info
     *
     * @mbg.generated
     */
    List<FreeMessageInfo> selectByExampleWithRowbounds(FreeMessageInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_info
     *
     * @mbg.generated
     */
    List<FreeMessageInfo> selectByExample(FreeMessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_info
     *
     * @mbg.generated
     */
    FreeMessageInfo selectByPrimaryKey(Integer freeMessageInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FreeMessageInfo record, @Param("example") FreeMessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FreeMessageInfo record, @Param("example") FreeMessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FreeMessageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FreeMessageInfo record);
}