package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.FreeMessageRoom;
import mm.aeon.com.zgen.entity.FreeMessageRoomExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FreeMessageRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_room
     *
     * @mbg.generated
     */
    long countByExample(FreeMessageRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_room
     *
     * @mbg.generated
     */
    int deleteByExample(FreeMessageRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_room
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer freeMessageRoomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_room
     *
     * @mbg.generated
     */
    int insert(FreeMessageRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_room
     *
     * @mbg.generated
     */
    int insertSelective(FreeMessageRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_room
     *
     * @mbg.generated
     */
    List<FreeMessageRoom> selectByExampleWithRowbounds(FreeMessageRoomExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_room
     *
     * @mbg.generated
     */
    List<FreeMessageRoom> selectByExample(FreeMessageRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_room
     *
     * @mbg.generated
     */
    FreeMessageRoom selectByPrimaryKey(Integer freeMessageRoomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_room
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FreeMessageRoom record, @Param("example") FreeMessageRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_room
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FreeMessageRoom record, @Param("example") FreeMessageRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_room
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FreeMessageRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_message_room
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FreeMessageRoom record);
}