package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.MainMenu;
import mm.aeon.com.zgen.entity.MainMenuExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MainMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.main_menu
     *
     * @mbg.generated
     */
    long countByExample(MainMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.main_menu
     *
     * @mbg.generated
     */
    int deleteByExample(MainMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.main_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer mainMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.main_menu
     *
     * @mbg.generated
     */
    int insert(MainMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.main_menu
     *
     * @mbg.generated
     */
    int insertSelective(MainMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.main_menu
     *
     * @mbg.generated
     */
    List<MainMenu> selectByExampleWithRowbounds(MainMenuExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.main_menu
     *
     * @mbg.generated
     */
    List<MainMenu> selectByExample(MainMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.main_menu
     *
     * @mbg.generated
     */
    MainMenu selectByPrimaryKey(Integer mainMenuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.main_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MainMenu record, @Param("example") MainMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.main_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MainMenu record, @Param("example") MainMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.main_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MainMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.main_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MainMenu record);
}