package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.MemberType;
import mm.aeon.com.zgen.entity.MemberTypeExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MemberTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_type
     *
     * @mbg.generated
     */
    long countByExample(MemberTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_type
     *
     * @mbg.generated
     */
    int deleteByExample(MemberTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer memberTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_type
     *
     * @mbg.generated
     */
    int insert(MemberType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_type
     *
     * @mbg.generated
     */
    int insertSelective(MemberType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_type
     *
     * @mbg.generated
     */
    List<MemberType> selectByExampleWithRowbounds(MemberTypeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_type
     *
     * @mbg.generated
     */
    List<MemberType> selectByExample(MemberTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_type
     *
     * @mbg.generated
     */
    MemberType selectByPrimaryKey(Integer memberTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MemberType record, @Param("example") MemberTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MemberType record, @Param("example") MemberTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MemberType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MemberType record);
}