package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.MemberInfo;
import mm.aeon.com.zgen.entity.MemberInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MemberInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_info
     *
     * @mbg.generated
     */
    long countByExample(MemberInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_info
     *
     * @mbg.generated
     */
    int deleteByExample(MemberInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_info
     *
     * @mbg.generated
     */
    int insert(MemberInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_info
     *
     * @mbg.generated
     */
    int insertSelective(MemberInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_info
     *
     * @mbg.generated
     */
    List<MemberInfo> selectByExampleWithRowbounds(MemberInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_info
     *
     * @mbg.generated
     */
    List<MemberInfo> selectByExample(MemberInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_info
     *
     * @mbg.generated
     */
    MemberInfo selectByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MemberInfo record, @Param("example") MemberInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MemberInfo record, @Param("example") MemberInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MemberInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.member_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MemberInfo record);
}