package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.MenuGroup;
import mm.aeon.com.zgen.entity.MenuGroupExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MenuGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.menu_group
     *
     * @mbg.generated
     */
    long countByExample(MenuGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.menu_group
     *
     * @mbg.generated
     */
    int deleteByExample(MenuGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.menu_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer menuGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.menu_group
     *
     * @mbg.generated
     */
    int insert(MenuGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.menu_group
     *
     * @mbg.generated
     */
    int insertSelective(MenuGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.menu_group
     *
     * @mbg.generated
     */
    List<MenuGroup> selectByExampleWithRowbounds(MenuGroupExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.menu_group
     *
     * @mbg.generated
     */
    List<MenuGroup> selectByExample(MenuGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.menu_group
     *
     * @mbg.generated
     */
    MenuGroup selectByPrimaryKey(Integer menuGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.menu_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MenuGroup record, @Param("example") MenuGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.menu_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MenuGroup record, @Param("example") MenuGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.menu_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MenuGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.menu_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MenuGroup record);
}