package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.MessageRoom;
import mm.aeon.com.zgen.entity.MessageRoomExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MessageRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_room
     *
     * @mbg.generated
     */
    long countByExample(MessageRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_room
     *
     * @mbg.generated
     */
    int deleteByExample(MessageRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_room
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer mesgRoomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_room
     *
     * @mbg.generated
     */
    int insert(MessageRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_room
     *
     * @mbg.generated
     */
    int insertSelective(MessageRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_room
     *
     * @mbg.generated
     */
    List<MessageRoom> selectByExampleWithRowbounds(MessageRoomExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_room
     *
     * @mbg.generated
     */
    List<MessageRoom> selectByExample(MessageRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_room
     *
     * @mbg.generated
     */
    MessageRoom selectByPrimaryKey(Integer mesgRoomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_room
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MessageRoom record, @Param("example") MessageRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_room
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MessageRoom record, @Param("example") MessageRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_room
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MessageRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_room
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MessageRoom record);
}