package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.MessageInfo;
import mm.aeon.com.zgen.entity.MessageInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MessageInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_info
     *
     * @mbg.generated
     */
    long countByExample(MessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_info
     *
     * @mbg.generated
     */
    int deleteByExample(MessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_info
     *
     * @mbg.generated
     */
    int insert(MessageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_info
     *
     * @mbg.generated
     */
    int insertSelective(MessageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_info
     *
     * @mbg.generated
     */
    List<MessageInfo> selectByExampleWithRowbounds(MessageInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_info
     *
     * @mbg.generated
     */
    List<MessageInfo> selectByExample(MessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_info
     *
     * @mbg.generated
     */
    MessageInfo selectByPrimaryKey(Integer messageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MessageInfo record, @Param("example") MessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MessageInfo record, @Param("example") MessageInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MessageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.message_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MessageInfo record);
}