package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.MobileVerConfig;
import mm.aeon.com.zgen.entity.MobileVerConfigExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MobileVerConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.mobile_ver_config
     *
     * @mbg.generated
     */
    long countByExample(MobileVerConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.mobile_ver_config
     *
     * @mbg.generated
     */
    int deleteByExample(MobileVerConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.mobile_ver_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.mobile_ver_config
     *
     * @mbg.generated
     */
    int insert(MobileVerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.mobile_ver_config
     *
     * @mbg.generated
     */
    int insertSelective(MobileVerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.mobile_ver_config
     *
     * @mbg.generated
     */
    List<MobileVerConfig> selectByExampleWithRowbounds(MobileVerConfigExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.mobile_ver_config
     *
     * @mbg.generated
     */
    List<MobileVerConfig> selectByExample(MobileVerConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.mobile_ver_config
     *
     * @mbg.generated
     */
    MobileVerConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.mobile_ver_config
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MobileVerConfig record, @Param("example") MobileVerConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.mobile_ver_config
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MobileVerConfig record, @Param("example") MobileVerConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.mobile_ver_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MobileVerConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.mobile_ver_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MobileVerConfig record);
}