package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.PasswordInfo;
import mm.aeon.com.zgen.entity.PasswordInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PasswordInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.password_info
     *
     * @mbg.generated
     */
    long countByExample(PasswordInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.password_info
     *
     * @mbg.generated
     */
    int deleteByExample(PasswordInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.password_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer passwordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.password_info
     *
     * @mbg.generated
     */
    int insert(PasswordInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.password_info
     *
     * @mbg.generated
     */
    int insertSelective(PasswordInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.password_info
     *
     * @mbg.generated
     */
    List<PasswordInfo> selectByExampleWithRowbounds(PasswordInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.password_info
     *
     * @mbg.generated
     */
    List<PasswordInfo> selectByExample(PasswordInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.password_info
     *
     * @mbg.generated
     */
    PasswordInfo selectByPrimaryKey(Integer passwordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.password_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PasswordInfo record, @Param("example") PasswordInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.password_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PasswordInfo record, @Param("example") PasswordInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.password_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PasswordInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.password_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PasswordInfo record);
}