package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.PlMessageRoom;
import mm.aeon.com.zgen.entity.PlMessageRoomExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PlMessageRoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.pl_message_room
     *
     * @mbg.generated
     */
    long countByExample(PlMessageRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.pl_message_room
     *
     * @mbg.generated
     */
    int deleteByExample(PlMessageRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.pl_message_room
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer plMesgRoomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.pl_message_room
     *
     * @mbg.generated
     */
    int insert(PlMessageRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.pl_message_room
     *
     * @mbg.generated
     */
    int insertSelective(PlMessageRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.pl_message_room
     *
     * @mbg.generated
     */
    List<PlMessageRoom> selectByExampleWithRowbounds(PlMessageRoomExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.pl_message_room
     *
     * @mbg.generated
     */
    List<PlMessageRoom> selectByExample(PlMessageRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.pl_message_room
     *
     * @mbg.generated
     */
    PlMessageRoom selectByPrimaryKey(Integer plMesgRoomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.pl_message_room
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PlMessageRoom record, @Param("example") PlMessageRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.pl_message_room
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PlMessageRoom record, @Param("example") PlMessageRoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.pl_message_room
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PlMessageRoom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.pl_message_room
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PlMessageRoom record);
}