package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.PromotionsInfo;
import mm.aeon.com.zgen.entity.PromotionsInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PromotionsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.promotions_info
     *
     * @mbg.generated
     */
    long countByExample(PromotionsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.promotions_info
     *
     * @mbg.generated
     */
    int deleteByExample(PromotionsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.promotions_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer promotionsInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.promotions_info
     *
     * @mbg.generated
     */
    int insert(PromotionsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.promotions_info
     *
     * @mbg.generated
     */
    int insertSelective(PromotionsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.promotions_info
     *
     * @mbg.generated
     */
    List<PromotionsInfo> selectByExampleWithRowbounds(PromotionsInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.promotions_info
     *
     * @mbg.generated
     */
    List<PromotionsInfo> selectByExample(PromotionsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.promotions_info
     *
     * @mbg.generated
     */
    PromotionsInfo selectByPrimaryKey(Integer promotionsInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.promotions_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PromotionsInfo record, @Param("example") PromotionsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.promotions_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PromotionsInfo record, @Param("example") PromotionsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.promotions_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PromotionsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.promotions_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PromotionsInfo record);
}