package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.ScheduleTime;
import mm.aeon.com.zgen.entity.ScheduleTimeExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ScheduleTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.schedule_time
     *
     * @mbg.generated
     */
    long countByExample(ScheduleTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.schedule_time
     *
     * @mbg.generated
     */
    int deleteByExample(ScheduleTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.schedule_time
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer scheduleTimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.schedule_time
     *
     * @mbg.generated
     */
    int insert(ScheduleTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.schedule_time
     *
     * @mbg.generated
     */
    int insertSelective(ScheduleTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.schedule_time
     *
     * @mbg.generated
     */
    List<ScheduleTime> selectByExampleWithRowbounds(ScheduleTimeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.schedule_time
     *
     * @mbg.generated
     */
    List<ScheduleTime> selectByExample(ScheduleTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.schedule_time
     *
     * @mbg.generated
     */
    ScheduleTime selectByPrimaryKey(Integer scheduleTimeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.schedule_time
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ScheduleTime record, @Param("example") ScheduleTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.schedule_time
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ScheduleTime record, @Param("example") ScheduleTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.schedule_time
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ScheduleTime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.schedule_time
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ScheduleTime record);
}