package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.ShopCoupon;
import mm.aeon.com.zgen.entity.ShopCouponExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ShopCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_coupon
     *
     * @mbg.generated
     */
    long countByExample(ShopCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_coupon
     *
     * @mbg.generated
     */
    int deleteByExample(ShopCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer shopCouponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_coupon
     *
     * @mbg.generated
     */
    int insert(ShopCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_coupon
     *
     * @mbg.generated
     */
    int insertSelective(ShopCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_coupon
     *
     * @mbg.generated
     */
    List<ShopCoupon> selectByExampleWithRowbounds(ShopCouponExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_coupon
     *
     * @mbg.generated
     */
    List<ShopCoupon> selectByExample(ShopCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_coupon
     *
     * @mbg.generated
     */
    ShopCoupon selectByPrimaryKey(Integer shopCouponId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_coupon
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShopCoupon record, @Param("example") ShopCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_coupon
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShopCoupon record, @Param("example") ShopCouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopCoupon record);
}