package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.ShopBranch;
import mm.aeon.com.zgen.entity.ShopBranchExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ShopBranchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_branch
     *
     * @mbg.generated
     */
    long countByExample(ShopBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_branch
     *
     * @mbg.generated
     */
    int deleteByExample(ShopBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_branch
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer branchId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_branch
     *
     * @mbg.generated
     */
    int insert(ShopBranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_branch
     *
     * @mbg.generated
     */
    int insertSelective(ShopBranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_branch
     *
     * @mbg.generated
     */
    List<ShopBranch> selectByExampleWithRowbounds(ShopBranchExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_branch
     *
     * @mbg.generated
     */
    List<ShopBranch> selectByExample(ShopBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_branch
     *
     * @mbg.generated
     */
    ShopBranch selectByPrimaryKey(Integer branchId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_branch
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ShopBranch record, @Param("example") ShopBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_branch
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ShopBranch record, @Param("example") ShopBranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_branch
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShopBranch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_branch
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShopBranch record);
}