package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.TelemarketingAgentInfo;
import mm.aeon.com.zgen.entity.TelemarketingAgentInfoExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TelemarketingAgentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.telemarketing_agent_info
     *
     * @mbg.generated
     */
    long countByExample(TelemarketingAgentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.telemarketing_agent_info
     *
     * @mbg.generated
     */
    int deleteByExample(TelemarketingAgentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.telemarketing_agent_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer telemarketingAgentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.telemarketing_agent_info
     *
     * @mbg.generated
     */
    int insert(TelemarketingAgentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.telemarketing_agent_info
     *
     * @mbg.generated
     */
    int insertSelective(TelemarketingAgentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.telemarketing_agent_info
     *
     * @mbg.generated
     */
    List<TelemarketingAgentInfo> selectByExampleWithRowbounds(TelemarketingAgentInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.telemarketing_agent_info
     *
     * @mbg.generated
     */
    List<TelemarketingAgentInfo> selectByExample(TelemarketingAgentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.telemarketing_agent_info
     *
     * @mbg.generated
     */
    TelemarketingAgentInfo selectByPrimaryKey(Integer telemarketingAgentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.telemarketing_agent_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TelemarketingAgentInfo record, @Param("example") TelemarketingAgentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.telemarketing_agent_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TelemarketingAgentInfo record, @Param("example") TelemarketingAgentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.telemarketing_agent_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TelemarketingAgentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.telemarketing_agent_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TelemarketingAgentInfo record);
}