package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.TermsAndConditions;
import mm.aeon.com.zgen.entity.TermsAndConditionsExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TermsAndConditionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.terms_and_conditions
     *
     * @mbg.generated
     */
    long countByExample(TermsAndConditionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.terms_and_conditions
     *
     * @mbg.generated
     */
    int deleteByExample(TermsAndConditionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.terms_and_conditions
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer termsAndConditionsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.terms_and_conditions
     *
     * @mbg.generated
     */
    int insert(TermsAndConditions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.terms_and_conditions
     *
     * @mbg.generated
     */
    int insertSelective(TermsAndConditions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.terms_and_conditions
     *
     * @mbg.generated
     */
    List<TermsAndConditions> selectByExampleWithRowbounds(TermsAndConditionsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.terms_and_conditions
     *
     * @mbg.generated
     */
    List<TermsAndConditions> selectByExample(TermsAndConditionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.terms_and_conditions
     *
     * @mbg.generated
     */
    TermsAndConditions selectByPrimaryKey(Integer termsAndConditionsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.terms_and_conditions
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TermsAndConditions record, @Param("example") TermsAndConditionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.terms_and_conditions
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TermsAndConditions record, @Param("example") TermsAndConditionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.terms_and_conditions
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TermsAndConditions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.terms_and_conditions
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TermsAndConditions record);
}