package mm.aeon.com.zgen.mapper;

import java.util.List;
import mm.aeon.com.zgen.entity.TestView;
import mm.aeon.com.zgen.entity.TestViewExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TestViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.test_view
     *
     * @mbg.generated
     */
    long countByExample(TestViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.test_view
     *
     * @mbg.generated
     */
    int deleteByExample(TestViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.test_view
     *
     * @mbg.generated
     */
    int insert(TestView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.test_view
     *
     * @mbg.generated
     */
    int insertSelective(TestView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.test_view
     *
     * @mbg.generated
     */
    List<TestView> selectByExampleWithRowbounds(TestViewExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.test_view
     *
     * @mbg.generated
     */
    List<TestView> selectByExample(TestViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.test_view
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TestView record, @Param("example") TestViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.test_view
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TestView record, @Param("example") TestViewExample example);
}