package mm.aeon.com.zgen.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AppUsageDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    public AppUsageDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAppUsageDetailIdIsNull() {
            addCriterion("app_usage_detail_id is null");
            return (Criteria) this;
        }

        public Criteria andAppUsageDetailIdIsNotNull() {
            addCriterion("app_usage_detail_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppUsageDetailIdEqualTo(Integer value) {
            addCriterion("app_usage_detail_id =", value, "appUsageDetailId");
            return (Criteria) this;
        }

        public Criteria andAppUsageDetailIdNotEqualTo(Integer value) {
            addCriterion("app_usage_detail_id <>", value, "appUsageDetailId");
            return (Criteria) this;
        }

        public Criteria andAppUsageDetailIdGreaterThan(Integer value) {
            addCriterion("app_usage_detail_id >", value, "appUsageDetailId");
            return (Criteria) this;
        }

        public Criteria andAppUsageDetailIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("app_usage_detail_id >=", value, "appUsageDetailId");
            return (Criteria) this;
        }

        public Criteria andAppUsageDetailIdLessThan(Integer value) {
            addCriterion("app_usage_detail_id <", value, "appUsageDetailId");
            return (Criteria) this;
        }

        public Criteria andAppUsageDetailIdLessThanOrEqualTo(Integer value) {
            addCriterion("app_usage_detail_id <=", value, "appUsageDetailId");
            return (Criteria) this;
        }

        public Criteria andAppUsageDetailIdIn(List<Integer> values) {
            addCriterion("app_usage_detail_id in", values, "appUsageDetailId");
            return (Criteria) this;
        }

        public Criteria andAppUsageDetailIdNotIn(List<Integer> values) {
            addCriterion("app_usage_detail_id not in", values, "appUsageDetailId");
            return (Criteria) this;
        }

        public Criteria andAppUsageDetailIdBetween(Integer value1, Integer value2) {
            addCriterion("app_usage_detail_id between", value1, value2, "appUsageDetailId");
            return (Criteria) this;
        }

        public Criteria andAppUsageDetailIdNotBetween(Integer value1, Integer value2) {
            addCriterion("app_usage_detail_id not between", value1, value2, "appUsageDetailId");
            return (Criteria) this;
        }

        public Criteria andAppUsageIdIsNull() {
            addCriterion("app_usage_id is null");
            return (Criteria) this;
        }

        public Criteria andAppUsageIdIsNotNull() {
            addCriterion("app_usage_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppUsageIdEqualTo(Integer value) {
            addCriterion("app_usage_id =", value, "appUsageId");
            return (Criteria) this;
        }

        public Criteria andAppUsageIdNotEqualTo(Integer value) {
            addCriterion("app_usage_id <>", value, "appUsageId");
            return (Criteria) this;
        }

        public Criteria andAppUsageIdGreaterThan(Integer value) {
            addCriterion("app_usage_id >", value, "appUsageId");
            return (Criteria) this;
        }

        public Criteria andAppUsageIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("app_usage_id >=", value, "appUsageId");
            return (Criteria) this;
        }

        public Criteria andAppUsageIdLessThan(Integer value) {
            addCriterion("app_usage_id <", value, "appUsageId");
            return (Criteria) this;
        }

        public Criteria andAppUsageIdLessThanOrEqualTo(Integer value) {
            addCriterion("app_usage_id <=", value, "appUsageId");
            return (Criteria) this;
        }

        public Criteria andAppUsageIdIn(List<Integer> values) {
            addCriterion("app_usage_id in", values, "appUsageId");
            return (Criteria) this;
        }

        public Criteria andAppUsageIdNotIn(List<Integer> values) {
            addCriterion("app_usage_id not in", values, "appUsageId");
            return (Criteria) this;
        }

        public Criteria andAppUsageIdBetween(Integer value1, Integer value2) {
            addCriterion("app_usage_id between", value1, value2, "appUsageId");
            return (Criteria) this;
        }

        public Criteria andAppUsageIdNotBetween(Integer value1, Integer value2) {
            addCriterion("app_usage_id not between", value1, value2, "appUsageId");
            return (Criteria) this;
        }

        public Criteria andStartUsageDateTimeIsNull() {
            addCriterion("start_usage_date_time is null");
            return (Criteria) this;
        }

        public Criteria andStartUsageDateTimeIsNotNull() {
            addCriterion("start_usage_date_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartUsageDateTimeEqualTo(Date value) {
            addCriterion("start_usage_date_time =", value, "startUsageDateTime");
            return (Criteria) this;
        }

        public Criteria andStartUsageDateTimeNotEqualTo(Date value) {
            addCriterion("start_usage_date_time <>", value, "startUsageDateTime");
            return (Criteria) this;
        }

        public Criteria andStartUsageDateTimeGreaterThan(Date value) {
            addCriterion("start_usage_date_time >", value, "startUsageDateTime");
            return (Criteria) this;
        }

        public Criteria andStartUsageDateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_usage_date_time >=", value, "startUsageDateTime");
            return (Criteria) this;
        }

        public Criteria andStartUsageDateTimeLessThan(Date value) {
            addCriterion("start_usage_date_time <", value, "startUsageDateTime");
            return (Criteria) this;
        }

        public Criteria andStartUsageDateTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_usage_date_time <=", value, "startUsageDateTime");
            return (Criteria) this;
        }

        public Criteria andStartUsageDateTimeIn(List<Date> values) {
            addCriterion("start_usage_date_time in", values, "startUsageDateTime");
            return (Criteria) this;
        }

        public Criteria andStartUsageDateTimeNotIn(List<Date> values) {
            addCriterion("start_usage_date_time not in", values, "startUsageDateTime");
            return (Criteria) this;
        }

        public Criteria andStartUsageDateTimeBetween(Date value1, Date value2) {
            addCriterion("start_usage_date_time between", value1, value2, "startUsageDateTime");
            return (Criteria) this;
        }

        public Criteria andStartUsageDateTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_usage_date_time not between", value1, value2, "startUsageDateTime");
            return (Criteria) this;
        }

        public Criteria andEndUsageDateTimeIsNull() {
            addCriterion("end_usage_date_time is null");
            return (Criteria) this;
        }

        public Criteria andEndUsageDateTimeIsNotNull() {
            addCriterion("end_usage_date_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndUsageDateTimeEqualTo(Date value) {
            addCriterion("end_usage_date_time =", value, "endUsageDateTime");
            return (Criteria) this;
        }

        public Criteria andEndUsageDateTimeNotEqualTo(Date value) {
            addCriterion("end_usage_date_time <>", value, "endUsageDateTime");
            return (Criteria) this;
        }

        public Criteria andEndUsageDateTimeGreaterThan(Date value) {
            addCriterion("end_usage_date_time >", value, "endUsageDateTime");
            return (Criteria) this;
        }

        public Criteria andEndUsageDateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_usage_date_time >=", value, "endUsageDateTime");
            return (Criteria) this;
        }

        public Criteria andEndUsageDateTimeLessThan(Date value) {
            addCriterion("end_usage_date_time <", value, "endUsageDateTime");
            return (Criteria) this;
        }

        public Criteria andEndUsageDateTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_usage_date_time <=", value, "endUsageDateTime");
            return (Criteria) this;
        }

        public Criteria andEndUsageDateTimeIn(List<Date> values) {
            addCriterion("end_usage_date_time in", values, "endUsageDateTime");
            return (Criteria) this;
        }

        public Criteria andEndUsageDateTimeNotIn(List<Date> values) {
            addCriterion("end_usage_date_time not in", values, "endUsageDateTime");
            return (Criteria) this;
        }

        public Criteria andEndUsageDateTimeBetween(Date value1, Date value2) {
            addCriterion("end_usage_date_time between", value1, value2, "endUsageDateTime");
            return (Criteria) this;
        }

        public Criteria andEndUsageDateTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_usage_date_time not between", value1, value2, "endUsageDateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vcs.app_usage_detail
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}