package mm.aeon.com.zgen.entity;

import java.util.Date;

public class AtBrand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.at_brand.brand_id
     *
     * @mbg.generated
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.at_brand.brand_name
     *
     * @mbg.generated
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.at_brand.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.at_brand.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.at_brand.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.at_brand.updated_time
     *
     * @mbg.generated
     */
    private Date updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.at_brand.del_flag
     *
     * @mbg.generated
     */
    private Short delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.at_brand.brand_code
     *
     * @mbg.generated
     */
    private String brandCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.at_brand.brand_id
     *
     * @return the value of vcs.at_brand.brand_id
     *
     * @mbg.generated
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.at_brand.brand_id
     *
     * @param brandId the value for vcs.at_brand.brand_id
     *
     * @mbg.generated
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.at_brand.brand_name
     *
     * @return the value of vcs.at_brand.brand_name
     *
     * @mbg.generated
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.at_brand.brand_name
     *
     * @param brandName the value for vcs.at_brand.brand_name
     *
     * @mbg.generated
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.at_brand.created_by
     *
     * @return the value of vcs.at_brand.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.at_brand.created_by
     *
     * @param createdBy the value for vcs.at_brand.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.at_brand.updated_by
     *
     * @return the value of vcs.at_brand.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.at_brand.updated_by
     *
     * @param updatedBy the value for vcs.at_brand.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.at_brand.created_time
     *
     * @return the value of vcs.at_brand.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.at_brand.created_time
     *
     * @param createdTime the value for vcs.at_brand.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.at_brand.updated_time
     *
     * @return the value of vcs.at_brand.updated_time
     *
     * @mbg.generated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.at_brand.updated_time
     *
     * @param updatedTime the value for vcs.at_brand.updated_time
     *
     * @mbg.generated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.at_brand.del_flag
     *
     * @return the value of vcs.at_brand.del_flag
     *
     * @mbg.generated
     */
    public Short getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.at_brand.del_flag
     *
     * @param delFlag the value for vcs.at_brand.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Short delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.at_brand.brand_code
     *
     * @return the value of vcs.at_brand.brand_code
     *
     * @mbg.generated
     */
    public String getBrandCode() {
        return brandCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.at_brand.brand_code
     *
     * @param brandCode the value for vcs.at_brand.brand_code
     *
     * @mbg.generated
     */
    public void setBrandCode(String brandCode) {
        this.brandCode = brandCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.at_brand
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", brandId=").append(brandId);
        sb.append(", brandName=").append(brandName);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", brandCode=").append(brandCode);
        sb.append("]");
        return sb.toString();
    }
}