package mm.aeon.com.zgen.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChatMessageExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vcs.chat_message
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vcs.chat_message
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vcs.chat_message
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.chat_message
     *
     * @mbg.generated
     */
    public ChatMessageExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.chat_message
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.chat_message
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.chat_message
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.chat_message
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.chat_message
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.chat_message
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.chat_message
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.chat_message
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.chat_message
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.chat_message
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vcs.chat_message
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andChatMessageIdIsNull() {
            addCriterion("chat_message_id is null");
            return (Criteria) this;
        }

        public Criteria andChatMessageIdIsNotNull() {
            addCriterion("chat_message_id is not null");
            return (Criteria) this;
        }

        public Criteria andChatMessageIdEqualTo(Integer value) {
            addCriterion("chat_message_id =", value, "chatMessageId");
            return (Criteria) this;
        }

        public Criteria andChatMessageIdNotEqualTo(Integer value) {
            addCriterion("chat_message_id <>", value, "chatMessageId");
            return (Criteria) this;
        }

        public Criteria andChatMessageIdGreaterThan(Integer value) {
            addCriterion("chat_message_id >", value, "chatMessageId");
            return (Criteria) this;
        }

        public Criteria andChatMessageIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("chat_message_id >=", value, "chatMessageId");
            return (Criteria) this;
        }

        public Criteria andChatMessageIdLessThan(Integer value) {
            addCriterion("chat_message_id <", value, "chatMessageId");
            return (Criteria) this;
        }

        public Criteria andChatMessageIdLessThanOrEqualTo(Integer value) {
            addCriterion("chat_message_id <=", value, "chatMessageId");
            return (Criteria) this;
        }

        public Criteria andChatMessageIdIn(List<Integer> values) {
            addCriterion("chat_message_id in", values, "chatMessageId");
            return (Criteria) this;
        }

        public Criteria andChatMessageIdNotIn(List<Integer> values) {
            addCriterion("chat_message_id not in", values, "chatMessageId");
            return (Criteria) this;
        }

        public Criteria andChatMessageIdBetween(Integer value1, Integer value2) {
            addCriterion("chat_message_id between", value1, value2, "chatMessageId");
            return (Criteria) this;
        }

        public Criteria andChatMessageIdNotBetween(Integer value1, Integer value2) {
            addCriterion("chat_message_id not between", value1, value2, "chatMessageId");
            return (Criteria) this;
        }

        public Criteria andDaProductTypeIdIsNull() {
            addCriterion("da_product_type_id is null");
            return (Criteria) this;
        }

        public Criteria andDaProductTypeIdIsNotNull() {
            addCriterion("da_product_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andDaProductTypeIdEqualTo(Integer value) {
            addCriterion("da_product_type_id =", value, "daProductTypeId");
            return (Criteria) this;
        }

        public Criteria andDaProductTypeIdNotEqualTo(Integer value) {
            addCriterion("da_product_type_id <>", value, "daProductTypeId");
            return (Criteria) this;
        }

        public Criteria andDaProductTypeIdGreaterThan(Integer value) {
            addCriterion("da_product_type_id >", value, "daProductTypeId");
            return (Criteria) this;
        }

        public Criteria andDaProductTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("da_product_type_id >=", value, "daProductTypeId");
            return (Criteria) this;
        }

        public Criteria andDaProductTypeIdLessThan(Integer value) {
            addCriterion("da_product_type_id <", value, "daProductTypeId");
            return (Criteria) this;
        }

        public Criteria andDaProductTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("da_product_type_id <=", value, "daProductTypeId");
            return (Criteria) this;
        }

        public Criteria andDaProductTypeIdIn(List<Integer> values) {
            addCriterion("da_product_type_id in", values, "daProductTypeId");
            return (Criteria) this;
        }

        public Criteria andDaProductTypeIdNotIn(List<Integer> values) {
            addCriterion("da_product_type_id not in", values, "daProductTypeId");
            return (Criteria) this;
        }

        public Criteria andDaProductTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("da_product_type_id between", value1, value2, "daProductTypeId");
            return (Criteria) this;
        }

        public Criteria andDaProductTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("da_product_type_id not between", value1, value2, "daProductTypeId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNull() {
            addCriterion("customer_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNotNull() {
            addCriterion("customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdEqualTo(Integer value) {
            addCriterion("customer_id =", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotEqualTo(Integer value) {
            addCriterion("customer_id <>", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThan(Integer value) {
            addCriterion("customer_id >", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("customer_id >=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThan(Integer value) {
            addCriterion("customer_id <", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThanOrEqualTo(Integer value) {
            addCriterion("customer_id <=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIn(List<Integer> values) {
            addCriterion("customer_id in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotIn(List<Integer> values) {
            addCriterion("customer_id not in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdBetween(Integer value1, Integer value2) {
            addCriterion("customer_id between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotBetween(Integer value1, Integer value2) {
            addCriterion("customer_id not between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNull() {
            addCriterion("brand_id is null");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNotNull() {
            addCriterion("brand_id is not null");
            return (Criteria) this;
        }

        public Criteria andBrandIdEqualTo(Integer value) {
            addCriterion("brand_id =", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotEqualTo(Integer value) {
            addCriterion("brand_id <>", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThan(Integer value) {
            addCriterion("brand_id >", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("brand_id >=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThan(Integer value) {
            addCriterion("brand_id <", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThanOrEqualTo(Integer value) {
            addCriterion("brand_id <=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdIn(List<Integer> values) {
            addCriterion("brand_id in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotIn(List<Integer> values) {
            addCriterion("brand_id not in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdBetween(Integer value1, Integer value2) {
            addCriterion("brand_id between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotBetween(Integer value1, Integer value2) {
            addCriterion("brand_id not between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andCustomerLocationIsNull() {
            addCriterion("customer_location is null");
            return (Criteria) this;
        }

        public Criteria andCustomerLocationIsNotNull() {
            addCriterion("customer_location is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerLocationEqualTo(String value) {
            addCriterion("customer_location =", value, "customerLocation");
            return (Criteria) this;
        }

        public Criteria andCustomerLocationNotEqualTo(String value) {
            addCriterion("customer_location <>", value, "customerLocation");
            return (Criteria) this;
        }

        public Criteria andCustomerLocationGreaterThan(String value) {
            addCriterion("customer_location >", value, "customerLocation");
            return (Criteria) this;
        }

        public Criteria andCustomerLocationGreaterThanOrEqualTo(String value) {
            addCriterion("customer_location >=", value, "customerLocation");
            return (Criteria) this;
        }

        public Criteria andCustomerLocationLessThan(String value) {
            addCriterion("customer_location <", value, "customerLocation");
            return (Criteria) this;
        }

        public Criteria andCustomerLocationLessThanOrEqualTo(String value) {
            addCriterion("customer_location <=", value, "customerLocation");
            return (Criteria) this;
        }

        public Criteria andCustomerLocationLike(String value) {
            addCriterion("customer_location like", value, "customerLocation");
            return (Criteria) this;
        }

        public Criteria andCustomerLocationNotLike(String value) {
            addCriterion("customer_location not like", value, "customerLocation");
            return (Criteria) this;
        }

        public Criteria andCustomerLocationIn(List<String> values) {
            addCriterion("customer_location in", values, "customerLocation");
            return (Criteria) this;
        }

        public Criteria andCustomerLocationNotIn(List<String> values) {
            addCriterion("customer_location not in", values, "customerLocation");
            return (Criteria) this;
        }

        public Criteria andCustomerLocationBetween(String value1, String value2) {
            addCriterion("customer_location between", value1, value2, "customerLocation");
            return (Criteria) this;
        }

        public Criteria andCustomerLocationNotBetween(String value1, String value2) {
            addCriterion("customer_location not between", value1, value2, "customerLocation");
            return (Criteria) this;
        }

        public Criteria andMessageContentIsNull() {
            addCriterion("message_content is null");
            return (Criteria) this;
        }

        public Criteria andMessageContentIsNotNull() {
            addCriterion("message_content is not null");
            return (Criteria) this;
        }

        public Criteria andMessageContentEqualTo(String value) {
            addCriterion("message_content =", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentNotEqualTo(String value) {
            addCriterion("message_content <>", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentGreaterThan(String value) {
            addCriterion("message_content >", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentGreaterThanOrEqualTo(String value) {
            addCriterion("message_content >=", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentLessThan(String value) {
            addCriterion("message_content <", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentLessThanOrEqualTo(String value) {
            addCriterion("message_content <=", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentLike(String value) {
            addCriterion("message_content like", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentNotLike(String value) {
            addCriterion("message_content not like", value, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentIn(List<String> values) {
            addCriterion("message_content in", values, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentNotIn(List<String> values) {
            addCriterion("message_content not in", values, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentBetween(String value1, String value2) {
            addCriterion("message_content between", value1, value2, "messageContent");
            return (Criteria) this;
        }

        public Criteria andMessageContentNotBetween(String value1, String value2) {
            addCriterion("message_content not between", value1, value2, "messageContent");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIsNull() {
            addCriterion("phone_no is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIsNotNull() {
            addCriterion("phone_no is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNoEqualTo(String value) {
            addCriterion("phone_no =", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotEqualTo(String value) {
            addCriterion("phone_no <>", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoGreaterThan(String value) {
            addCriterion("phone_no >", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoGreaterThanOrEqualTo(String value) {
            addCriterion("phone_no >=", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLessThan(String value) {
            addCriterion("phone_no <", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLessThanOrEqualTo(String value) {
            addCriterion("phone_no <=", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLike(String value) {
            addCriterion("phone_no like", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotLike(String value) {
            addCriterion("phone_no not like", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIn(List<String> values) {
            addCriterion("phone_no in", values, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotIn(List<String> values) {
            addCriterion("phone_no not in", values, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoBetween(String value1, String value2) {
            addCriterion("phone_no between", value1, value2, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotBetween(String value1, String value2) {
            addCriterion("phone_no not between", value1, value2, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andUrlLinkIsNull() {
            addCriterion("url_link is null");
            return (Criteria) this;
        }

        public Criteria andUrlLinkIsNotNull() {
            addCriterion("url_link is not null");
            return (Criteria) this;
        }

        public Criteria andUrlLinkEqualTo(String value) {
            addCriterion("url_link =", value, "urlLink");
            return (Criteria) this;
        }

        public Criteria andUrlLinkNotEqualTo(String value) {
            addCriterion("url_link <>", value, "urlLink");
            return (Criteria) this;
        }

        public Criteria andUrlLinkGreaterThan(String value) {
            addCriterion("url_link >", value, "urlLink");
            return (Criteria) this;
        }

        public Criteria andUrlLinkGreaterThanOrEqualTo(String value) {
            addCriterion("url_link >=", value, "urlLink");
            return (Criteria) this;
        }

        public Criteria andUrlLinkLessThan(String value) {
            addCriterion("url_link <", value, "urlLink");
            return (Criteria) this;
        }

        public Criteria andUrlLinkLessThanOrEqualTo(String value) {
            addCriterion("url_link <=", value, "urlLink");
            return (Criteria) this;
        }

        public Criteria andUrlLinkLike(String value) {
            addCriterion("url_link like", value, "urlLink");
            return (Criteria) this;
        }

        public Criteria andUrlLinkNotLike(String value) {
            addCriterion("url_link not like", value, "urlLink");
            return (Criteria) this;
        }

        public Criteria andUrlLinkIn(List<String> values) {
            addCriterion("url_link in", values, "urlLink");
            return (Criteria) this;
        }

        public Criteria andUrlLinkNotIn(List<String> values) {
            addCriterion("url_link not in", values, "urlLink");
            return (Criteria) this;
        }

        public Criteria andUrlLinkBetween(String value1, String value2) {
            addCriterion("url_link between", value1, value2, "urlLink");
            return (Criteria) this;
        }

        public Criteria andUrlLinkNotBetween(String value1, String value2) {
            addCriterion("url_link not between", value1, value2, "urlLink");
            return (Criteria) this;
        }

        public Criteria andSendTimeIsNull() {
            addCriterion("send_time is null");
            return (Criteria) this;
        }

        public Criteria andSendTimeIsNotNull() {
            addCriterion("send_time is not null");
            return (Criteria) this;
        }

        public Criteria andSendTimeEqualTo(Date value) {
            addCriterion("send_time =", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotEqualTo(Date value) {
            addCriterion("send_time <>", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeGreaterThan(Date value) {
            addCriterion("send_time >", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("send_time >=", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeLessThan(Date value) {
            addCriterion("send_time <", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeLessThanOrEqualTo(Date value) {
            addCriterion("send_time <=", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeIn(List<Date> values) {
            addCriterion("send_time in", values, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotIn(List<Date> values) {
            addCriterion("send_time not in", values, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeBetween(Date value1, Date value2) {
            addCriterion("send_time between", value1, value2, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotBetween(Date value1, Date value2) {
            addCriterion("send_time not between", value1, value2, "sendTime");
            return (Criteria) this;
        }

        public Criteria andTelemarketingAgentIdIsNull() {
            addCriterion("telemarketing_agent_id is null");
            return (Criteria) this;
        }

        public Criteria andTelemarketingAgentIdIsNotNull() {
            addCriterion("telemarketing_agent_id is not null");
            return (Criteria) this;
        }

        public Criteria andTelemarketingAgentIdEqualTo(Integer value) {
            addCriterion("telemarketing_agent_id =", value, "telemarketingAgentId");
            return (Criteria) this;
        }

        public Criteria andTelemarketingAgentIdNotEqualTo(Integer value) {
            addCriterion("telemarketing_agent_id <>", value, "telemarketingAgentId");
            return (Criteria) this;
        }

        public Criteria andTelemarketingAgentIdGreaterThan(Integer value) {
            addCriterion("telemarketing_agent_id >", value, "telemarketingAgentId");
            return (Criteria) this;
        }

        public Criteria andTelemarketingAgentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("telemarketing_agent_id >=", value, "telemarketingAgentId");
            return (Criteria) this;
        }

        public Criteria andTelemarketingAgentIdLessThan(Integer value) {
            addCriterion("telemarketing_agent_id <", value, "telemarketingAgentId");
            return (Criteria) this;
        }

        public Criteria andTelemarketingAgentIdLessThanOrEqualTo(Integer value) {
            addCriterion("telemarketing_agent_id <=", value, "telemarketingAgentId");
            return (Criteria) this;
        }

        public Criteria andTelemarketingAgentIdIn(List<Integer> values) {
            addCriterion("telemarketing_agent_id in", values, "telemarketingAgentId");
            return (Criteria) this;
        }

        public Criteria andTelemarketingAgentIdNotIn(List<Integer> values) {
            addCriterion("telemarketing_agent_id not in", values, "telemarketingAgentId");
            return (Criteria) this;
        }

        public Criteria andTelemarketingAgentIdBetween(Integer value1, Integer value2) {
            addCriterion("telemarketing_agent_id between", value1, value2, "telemarketingAgentId");
            return (Criteria) this;
        }

        public Criteria andTelemarketingAgentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("telemarketing_agent_id not between", value1, value2, "telemarketingAgentId");
            return (Criteria) this;
        }

        public Criteria andOpSendFlagIsNull() {
            addCriterion("op_send_flag is null");
            return (Criteria) this;
        }

        public Criteria andOpSendFlagIsNotNull() {
            addCriterion("op_send_flag is not null");
            return (Criteria) this;
        }

        public Criteria andOpSendFlagEqualTo(Integer value) {
            addCriterion("op_send_flag =", value, "opSendFlag");
            return (Criteria) this;
        }

        public Criteria andOpSendFlagNotEqualTo(Integer value) {
            addCriterion("op_send_flag <>", value, "opSendFlag");
            return (Criteria) this;
        }

        public Criteria andOpSendFlagGreaterThan(Integer value) {
            addCriterion("op_send_flag >", value, "opSendFlag");
            return (Criteria) this;
        }

        public Criteria andOpSendFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("op_send_flag >=", value, "opSendFlag");
            return (Criteria) this;
        }

        public Criteria andOpSendFlagLessThan(Integer value) {
            addCriterion("op_send_flag <", value, "opSendFlag");
            return (Criteria) this;
        }

        public Criteria andOpSendFlagLessThanOrEqualTo(Integer value) {
            addCriterion("op_send_flag <=", value, "opSendFlag");
            return (Criteria) this;
        }

        public Criteria andOpSendFlagIn(List<Integer> values) {
            addCriterion("op_send_flag in", values, "opSendFlag");
            return (Criteria) this;
        }

        public Criteria andOpSendFlagNotIn(List<Integer> values) {
            addCriterion("op_send_flag not in", values, "opSendFlag");
            return (Criteria) this;
        }

        public Criteria andOpSendFlagBetween(Integer value1, Integer value2) {
            addCriterion("op_send_flag between", value1, value2, "opSendFlag");
            return (Criteria) this;
        }

        public Criteria andOpSendFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("op_send_flag not between", value1, value2, "opSendFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Short value) {
            addCriterion("del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Short value) {
            addCriterion("del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Short value) {
            addCriterion("del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Short value) {
            addCriterion("del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Short value) {
            addCriterion("del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Short value) {
            addCriterion("del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Short> values) {
            addCriterion("del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Short> values) {
            addCriterion("del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Short value1, Short value2) {
            addCriterion("del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Short value1, Short value2) {
            addCriterion("del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andReadFlagIsNull() {
            addCriterion("read_flag is null");
            return (Criteria) this;
        }

        public Criteria andReadFlagIsNotNull() {
            addCriterion("read_flag is not null");
            return (Criteria) this;
        }

        public Criteria andReadFlagEqualTo(Integer value) {
            addCriterion("read_flag =", value, "readFlag");
            return (Criteria) this;
        }

        public Criteria andReadFlagNotEqualTo(Integer value) {
            addCriterion("read_flag <>", value, "readFlag");
            return (Criteria) this;
        }

        public Criteria andReadFlagGreaterThan(Integer value) {
            addCriterion("read_flag >", value, "readFlag");
            return (Criteria) this;
        }

        public Criteria andReadFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("read_flag >=", value, "readFlag");
            return (Criteria) this;
        }

        public Criteria andReadFlagLessThan(Integer value) {
            addCriterion("read_flag <", value, "readFlag");
            return (Criteria) this;
        }

        public Criteria andReadFlagLessThanOrEqualTo(Integer value) {
            addCriterion("read_flag <=", value, "readFlag");
            return (Criteria) this;
        }

        public Criteria andReadFlagIn(List<Integer> values) {
            addCriterion("read_flag in", values, "readFlag");
            return (Criteria) this;
        }

        public Criteria andReadFlagNotIn(List<Integer> values) {
            addCriterion("read_flag not in", values, "readFlag");
            return (Criteria) this;
        }

        public Criteria andReadFlagBetween(Integer value1, Integer value2) {
            addCriterion("read_flag between", value1, value2, "readFlag");
            return (Criteria) this;
        }

        public Criteria andReadFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("read_flag not between", value1, value2, "readFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vcs.chat_message
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vcs.chat_message
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}