package mm.aeon.com.zgen.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CouponInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vcs.coupon_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vcs.coupon_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table vcs.coupon_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_info
     *
     * @mbg.generated
     */
    public CouponInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.coupon_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vcs.coupon_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCouponIdIsNull() {
            addCriterion("coupon_id is null");
            return (Criteria) this;
        }

        public Criteria andCouponIdIsNotNull() {
            addCriterion("coupon_id is not null");
            return (Criteria) this;
        }

        public Criteria andCouponIdEqualTo(Integer value) {
            addCriterion("coupon_id =", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotEqualTo(Integer value) {
            addCriterion("coupon_id <>", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdGreaterThan(Integer value) {
            addCriterion("coupon_id >", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("coupon_id >=", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdLessThan(Integer value) {
            addCriterion("coupon_id <", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdLessThanOrEqualTo(Integer value) {
            addCriterion("coupon_id <=", value, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdIn(List<Integer> values) {
            addCriterion("coupon_id in", values, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotIn(List<Integer> values) {
            addCriterion("coupon_id not in", values, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdBetween(Integer value1, Integer value2) {
            addCriterion("coupon_id between", value1, value2, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponIdNotBetween(Integer value1, Integer value2) {
            addCriterion("coupon_id not between", value1, value2, "couponId");
            return (Criteria) this;
        }

        public Criteria andCouponCodeIsNull() {
            addCriterion("coupon_code is null");
            return (Criteria) this;
        }

        public Criteria andCouponCodeIsNotNull() {
            addCriterion("coupon_code is not null");
            return (Criteria) this;
        }

        public Criteria andCouponCodeEqualTo(String value) {
            addCriterion("coupon_code =", value, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeNotEqualTo(String value) {
            addCriterion("coupon_code <>", value, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeGreaterThan(String value) {
            addCriterion("coupon_code >", value, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeGreaterThanOrEqualTo(String value) {
            addCriterion("coupon_code >=", value, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeLessThan(String value) {
            addCriterion("coupon_code <", value, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeLessThanOrEqualTo(String value) {
            addCriterion("coupon_code <=", value, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeLike(String value) {
            addCriterion("coupon_code like", value, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeNotLike(String value) {
            addCriterion("coupon_code not like", value, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeIn(List<String> values) {
            addCriterion("coupon_code in", values, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeNotIn(List<String> values) {
            addCriterion("coupon_code not in", values, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeBetween(String value1, String value2) {
            addCriterion("coupon_code between", value1, value2, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponCodeNotBetween(String value1, String value2) {
            addCriterion("coupon_code not between", value1, value2, "couponCode");
            return (Criteria) this;
        }

        public Criteria andCouponNameMmIsNull() {
            addCriterion("coupon_name_mm is null");
            return (Criteria) this;
        }

        public Criteria andCouponNameMmIsNotNull() {
            addCriterion("coupon_name_mm is not null");
            return (Criteria) this;
        }

        public Criteria andCouponNameMmEqualTo(String value) {
            addCriterion("coupon_name_mm =", value, "couponNameMm");
            return (Criteria) this;
        }

        public Criteria andCouponNameMmNotEqualTo(String value) {
            addCriterion("coupon_name_mm <>", value, "couponNameMm");
            return (Criteria) this;
        }

        public Criteria andCouponNameMmGreaterThan(String value) {
            addCriterion("coupon_name_mm >", value, "couponNameMm");
            return (Criteria) this;
        }

        public Criteria andCouponNameMmGreaterThanOrEqualTo(String value) {
            addCriterion("coupon_name_mm >=", value, "couponNameMm");
            return (Criteria) this;
        }

        public Criteria andCouponNameMmLessThan(String value) {
            addCriterion("coupon_name_mm <", value, "couponNameMm");
            return (Criteria) this;
        }

        public Criteria andCouponNameMmLessThanOrEqualTo(String value) {
            addCriterion("coupon_name_mm <=", value, "couponNameMm");
            return (Criteria) this;
        }

        public Criteria andCouponNameMmLike(String value) {
            addCriterion("coupon_name_mm like", value, "couponNameMm");
            return (Criteria) this;
        }

        public Criteria andCouponNameMmNotLike(String value) {
            addCriterion("coupon_name_mm not like", value, "couponNameMm");
            return (Criteria) this;
        }

        public Criteria andCouponNameMmIn(List<String> values) {
            addCriterion("coupon_name_mm in", values, "couponNameMm");
            return (Criteria) this;
        }

        public Criteria andCouponNameMmNotIn(List<String> values) {
            addCriterion("coupon_name_mm not in", values, "couponNameMm");
            return (Criteria) this;
        }

        public Criteria andCouponNameMmBetween(String value1, String value2) {
            addCriterion("coupon_name_mm between", value1, value2, "couponNameMm");
            return (Criteria) this;
        }

        public Criteria andCouponNameMmNotBetween(String value1, String value2) {
            addCriterion("coupon_name_mm not between", value1, value2, "couponNameMm");
            return (Criteria) this;
        }

        public Criteria andCouponNameEnIsNull() {
            addCriterion("coupon_name_en is null");
            return (Criteria) this;
        }

        public Criteria andCouponNameEnIsNotNull() {
            addCriterion("coupon_name_en is not null");
            return (Criteria) this;
        }

        public Criteria andCouponNameEnEqualTo(String value) {
            addCriterion("coupon_name_en =", value, "couponNameEn");
            return (Criteria) this;
        }

        public Criteria andCouponNameEnNotEqualTo(String value) {
            addCriterion("coupon_name_en <>", value, "couponNameEn");
            return (Criteria) this;
        }

        public Criteria andCouponNameEnGreaterThan(String value) {
            addCriterion("coupon_name_en >", value, "couponNameEn");
            return (Criteria) this;
        }

        public Criteria andCouponNameEnGreaterThanOrEqualTo(String value) {
            addCriterion("coupon_name_en >=", value, "couponNameEn");
            return (Criteria) this;
        }

        public Criteria andCouponNameEnLessThan(String value) {
            addCriterion("coupon_name_en <", value, "couponNameEn");
            return (Criteria) this;
        }

        public Criteria andCouponNameEnLessThanOrEqualTo(String value) {
            addCriterion("coupon_name_en <=", value, "couponNameEn");
            return (Criteria) this;
        }

        public Criteria andCouponNameEnLike(String value) {
            addCriterion("coupon_name_en like", value, "couponNameEn");
            return (Criteria) this;
        }

        public Criteria andCouponNameEnNotLike(String value) {
            addCriterion("coupon_name_en not like", value, "couponNameEn");
            return (Criteria) this;
        }

        public Criteria andCouponNameEnIn(List<String> values) {
            addCriterion("coupon_name_en in", values, "couponNameEn");
            return (Criteria) this;
        }

        public Criteria andCouponNameEnNotIn(List<String> values) {
            addCriterion("coupon_name_en not in", values, "couponNameEn");
            return (Criteria) this;
        }

        public Criteria andCouponNameEnBetween(String value1, String value2) {
            addCriterion("coupon_name_en between", value1, value2, "couponNameEn");
            return (Criteria) this;
        }

        public Criteria andCouponNameEnNotBetween(String value1, String value2) {
            addCriterion("coupon_name_en not between", value1, value2, "couponNameEn");
            return (Criteria) this;
        }

        public Criteria andDescriptionMmIsNull() {
            addCriterion("description_mm is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionMmIsNotNull() {
            addCriterion("description_mm is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionMmEqualTo(String value) {
            addCriterion("description_mm =", value, "descriptionMm");
            return (Criteria) this;
        }

        public Criteria andDescriptionMmNotEqualTo(String value) {
            addCriterion("description_mm <>", value, "descriptionMm");
            return (Criteria) this;
        }

        public Criteria andDescriptionMmGreaterThan(String value) {
            addCriterion("description_mm >", value, "descriptionMm");
            return (Criteria) this;
        }

        public Criteria andDescriptionMmGreaterThanOrEqualTo(String value) {
            addCriterion("description_mm >=", value, "descriptionMm");
            return (Criteria) this;
        }

        public Criteria andDescriptionMmLessThan(String value) {
            addCriterion("description_mm <", value, "descriptionMm");
            return (Criteria) this;
        }

        public Criteria andDescriptionMmLessThanOrEqualTo(String value) {
            addCriterion("description_mm <=", value, "descriptionMm");
            return (Criteria) this;
        }

        public Criteria andDescriptionMmLike(String value) {
            addCriterion("description_mm like", value, "descriptionMm");
            return (Criteria) this;
        }

        public Criteria andDescriptionMmNotLike(String value) {
            addCriterion("description_mm not like", value, "descriptionMm");
            return (Criteria) this;
        }

        public Criteria andDescriptionMmIn(List<String> values) {
            addCriterion("description_mm in", values, "descriptionMm");
            return (Criteria) this;
        }

        public Criteria andDescriptionMmNotIn(List<String> values) {
            addCriterion("description_mm not in", values, "descriptionMm");
            return (Criteria) this;
        }

        public Criteria andDescriptionMmBetween(String value1, String value2) {
            addCriterion("description_mm between", value1, value2, "descriptionMm");
            return (Criteria) this;
        }

        public Criteria andDescriptionMmNotBetween(String value1, String value2) {
            addCriterion("description_mm not between", value1, value2, "descriptionMm");
            return (Criteria) this;
        }

        public Criteria andDescriptionEnIsNull() {
            addCriterion("description_en is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEnIsNotNull() {
            addCriterion("description_en is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEnEqualTo(String value) {
            addCriterion("description_en =", value, "descriptionEn");
            return (Criteria) this;
        }

        public Criteria andDescriptionEnNotEqualTo(String value) {
            addCriterion("description_en <>", value, "descriptionEn");
            return (Criteria) this;
        }

        public Criteria andDescriptionEnGreaterThan(String value) {
            addCriterion("description_en >", value, "descriptionEn");
            return (Criteria) this;
        }

        public Criteria andDescriptionEnGreaterThanOrEqualTo(String value) {
            addCriterion("description_en >=", value, "descriptionEn");
            return (Criteria) this;
        }

        public Criteria andDescriptionEnLessThan(String value) {
            addCriterion("description_en <", value, "descriptionEn");
            return (Criteria) this;
        }

        public Criteria andDescriptionEnLessThanOrEqualTo(String value) {
            addCriterion("description_en <=", value, "descriptionEn");
            return (Criteria) this;
        }

        public Criteria andDescriptionEnLike(String value) {
            addCriterion("description_en like", value, "descriptionEn");
            return (Criteria) this;
        }

        public Criteria andDescriptionEnNotLike(String value) {
            addCriterion("description_en not like", value, "descriptionEn");
            return (Criteria) this;
        }

        public Criteria andDescriptionEnIn(List<String> values) {
            addCriterion("description_en in", values, "descriptionEn");
            return (Criteria) this;
        }

        public Criteria andDescriptionEnNotIn(List<String> values) {
            addCriterion("description_en not in", values, "descriptionEn");
            return (Criteria) this;
        }

        public Criteria andDescriptionEnBetween(String value1, String value2) {
            addCriterion("description_en between", value1, value2, "descriptionEn");
            return (Criteria) this;
        }

        public Criteria andDescriptionEnNotBetween(String value1, String value2) {
            addCriterion("description_en not between", value1, value2, "descriptionEn");
            return (Criteria) this;
        }

        public Criteria andCouponAmountIsNull() {
            addCriterion("coupon_amount is null");
            return (Criteria) this;
        }

        public Criteria andCouponAmountIsNotNull() {
            addCriterion("coupon_amount is not null");
            return (Criteria) this;
        }

        public Criteria andCouponAmountEqualTo(Long value) {
            addCriterion("coupon_amount =", value, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountNotEqualTo(Long value) {
            addCriterion("coupon_amount <>", value, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountGreaterThan(Long value) {
            addCriterion("coupon_amount >", value, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("coupon_amount >=", value, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountLessThan(Long value) {
            addCriterion("coupon_amount <", value, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountLessThanOrEqualTo(Long value) {
            addCriterion("coupon_amount <=", value, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountIn(List<Long> values) {
            addCriterion("coupon_amount in", values, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountNotIn(List<Long> values) {
            addCriterion("coupon_amount not in", values, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountBetween(Long value1, Long value2) {
            addCriterion("coupon_amount between", value1, value2, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andCouponAmountNotBetween(Long value1, Long value2) {
            addCriterion("coupon_amount not between", value1, value2, "couponAmount");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceIsNull() {
            addCriterion("goods_price is null");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceIsNotNull() {
            addCriterion("goods_price is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceEqualTo(Long value) {
            addCriterion("goods_price =", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceNotEqualTo(Long value) {
            addCriterion("goods_price <>", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceGreaterThan(Long value) {
            addCriterion("goods_price >", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceGreaterThanOrEqualTo(Long value) {
            addCriterion("goods_price >=", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceLessThan(Long value) {
            addCriterion("goods_price <", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceLessThanOrEqualTo(Long value) {
            addCriterion("goods_price <=", value, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceIn(List<Long> values) {
            addCriterion("goods_price in", values, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceNotIn(List<Long> values) {
            addCriterion("goods_price not in", values, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceBetween(Long value1, Long value2) {
            addCriterion("goods_price between", value1, value2, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andGoodsPriceNotBetween(Long value1, Long value2) {
            addCriterion("goods_price not between", value1, value2, "goodsPrice");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeIsNull() {
            addCriterion("expire_time is null");
            return (Criteria) this;
        }

        public Criteria andExpireTimeIsNotNull() {
            addCriterion("expire_time is not null");
            return (Criteria) this;
        }

        public Criteria andExpireTimeEqualTo(Date value) {
            addCriterion("expire_time =", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeNotEqualTo(Date value) {
            addCriterion("expire_time <>", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeGreaterThan(Date value) {
            addCriterion("expire_time >", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("expire_time >=", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeLessThan(Date value) {
            addCriterion("expire_time <", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeLessThanOrEqualTo(Date value) {
            addCriterion("expire_time <=", value, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeIn(List<Date> values) {
            addCriterion("expire_time in", values, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeNotIn(List<Date> values) {
            addCriterion("expire_time not in", values, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeBetween(Date value1, Date value2) {
            addCriterion("expire_time between", value1, value2, "expireTime");
            return (Criteria) this;
        }

        public Criteria andExpireTimeNotBetween(Date value1, Date value2) {
            addCriterion("expire_time not between", value1, value2, "expireTime");
            return (Criteria) this;
        }

        public Criteria andDiscountUnitIsNull() {
            addCriterion("discount_unit is null");
            return (Criteria) this;
        }

        public Criteria andDiscountUnitIsNotNull() {
            addCriterion("discount_unit is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountUnitEqualTo(String value) {
            addCriterion("discount_unit =", value, "discountUnit");
            return (Criteria) this;
        }

        public Criteria andDiscountUnitNotEqualTo(String value) {
            addCriterion("discount_unit <>", value, "discountUnit");
            return (Criteria) this;
        }

        public Criteria andDiscountUnitGreaterThan(String value) {
            addCriterion("discount_unit >", value, "discountUnit");
            return (Criteria) this;
        }

        public Criteria andDiscountUnitGreaterThanOrEqualTo(String value) {
            addCriterion("discount_unit >=", value, "discountUnit");
            return (Criteria) this;
        }

        public Criteria andDiscountUnitLessThan(String value) {
            addCriterion("discount_unit <", value, "discountUnit");
            return (Criteria) this;
        }

        public Criteria andDiscountUnitLessThanOrEqualTo(String value) {
            addCriterion("discount_unit <=", value, "discountUnit");
            return (Criteria) this;
        }

        public Criteria andDiscountUnitLike(String value) {
            addCriterion("discount_unit like", value, "discountUnit");
            return (Criteria) this;
        }

        public Criteria andDiscountUnitNotLike(String value) {
            addCriterion("discount_unit not like", value, "discountUnit");
            return (Criteria) this;
        }

        public Criteria andDiscountUnitIn(List<String> values) {
            addCriterion("discount_unit in", values, "discountUnit");
            return (Criteria) this;
        }

        public Criteria andDiscountUnitNotIn(List<String> values) {
            addCriterion("discount_unit not in", values, "discountUnit");
            return (Criteria) this;
        }

        public Criteria andDiscountUnitBetween(String value1, String value2) {
            addCriterion("discount_unit between", value1, value2, "discountUnit");
            return (Criteria) this;
        }

        public Criteria andDiscountUnitNotBetween(String value1, String value2) {
            addCriterion("discount_unit not between", value1, value2, "discountUnit");
            return (Criteria) this;
        }

        public Criteria andUnuseImagePathIsNull() {
            addCriterion("unuse_image_path is null");
            return (Criteria) this;
        }

        public Criteria andUnuseImagePathIsNotNull() {
            addCriterion("unuse_image_path is not null");
            return (Criteria) this;
        }

        public Criteria andUnuseImagePathEqualTo(String value) {
            addCriterion("unuse_image_path =", value, "unuseImagePath");
            return (Criteria) this;
        }

        public Criteria andUnuseImagePathNotEqualTo(String value) {
            addCriterion("unuse_image_path <>", value, "unuseImagePath");
            return (Criteria) this;
        }

        public Criteria andUnuseImagePathGreaterThan(String value) {
            addCriterion("unuse_image_path >", value, "unuseImagePath");
            return (Criteria) this;
        }

        public Criteria andUnuseImagePathGreaterThanOrEqualTo(String value) {
            addCriterion("unuse_image_path >=", value, "unuseImagePath");
            return (Criteria) this;
        }

        public Criteria andUnuseImagePathLessThan(String value) {
            addCriterion("unuse_image_path <", value, "unuseImagePath");
            return (Criteria) this;
        }

        public Criteria andUnuseImagePathLessThanOrEqualTo(String value) {
            addCriterion("unuse_image_path <=", value, "unuseImagePath");
            return (Criteria) this;
        }

        public Criteria andUnuseImagePathLike(String value) {
            addCriterion("unuse_image_path like", value, "unuseImagePath");
            return (Criteria) this;
        }

        public Criteria andUnuseImagePathNotLike(String value) {
            addCriterion("unuse_image_path not like", value, "unuseImagePath");
            return (Criteria) this;
        }

        public Criteria andUnuseImagePathIn(List<String> values) {
            addCriterion("unuse_image_path in", values, "unuseImagePath");
            return (Criteria) this;
        }

        public Criteria andUnuseImagePathNotIn(List<String> values) {
            addCriterion("unuse_image_path not in", values, "unuseImagePath");
            return (Criteria) this;
        }

        public Criteria andUnuseImagePathBetween(String value1, String value2) {
            addCriterion("unuse_image_path between", value1, value2, "unuseImagePath");
            return (Criteria) this;
        }

        public Criteria andUnuseImagePathNotBetween(String value1, String value2) {
            addCriterion("unuse_image_path not between", value1, value2, "unuseImagePath");
            return (Criteria) this;
        }

        public Criteria andUseImagePathIsNull() {
            addCriterion("use_image_path is null");
            return (Criteria) this;
        }

        public Criteria andUseImagePathIsNotNull() {
            addCriterion("use_image_path is not null");
            return (Criteria) this;
        }

        public Criteria andUseImagePathEqualTo(String value) {
            addCriterion("use_image_path =", value, "useImagePath");
            return (Criteria) this;
        }

        public Criteria andUseImagePathNotEqualTo(String value) {
            addCriterion("use_image_path <>", value, "useImagePath");
            return (Criteria) this;
        }

        public Criteria andUseImagePathGreaterThan(String value) {
            addCriterion("use_image_path >", value, "useImagePath");
            return (Criteria) this;
        }

        public Criteria andUseImagePathGreaterThanOrEqualTo(String value) {
            addCriterion("use_image_path >=", value, "useImagePath");
            return (Criteria) this;
        }

        public Criteria andUseImagePathLessThan(String value) {
            addCriterion("use_image_path <", value, "useImagePath");
            return (Criteria) this;
        }

        public Criteria andUseImagePathLessThanOrEqualTo(String value) {
            addCriterion("use_image_path <=", value, "useImagePath");
            return (Criteria) this;
        }

        public Criteria andUseImagePathLike(String value) {
            addCriterion("use_image_path like", value, "useImagePath");
            return (Criteria) this;
        }

        public Criteria andUseImagePathNotLike(String value) {
            addCriterion("use_image_path not like", value, "useImagePath");
            return (Criteria) this;
        }

        public Criteria andUseImagePathIn(List<String> values) {
            addCriterion("use_image_path in", values, "useImagePath");
            return (Criteria) this;
        }

        public Criteria andUseImagePathNotIn(List<String> values) {
            addCriterion("use_image_path not in", values, "useImagePath");
            return (Criteria) this;
        }

        public Criteria andUseImagePathBetween(String value1, String value2) {
            addCriterion("use_image_path between", value1, value2, "useImagePath");
            return (Criteria) this;
        }

        public Criteria andUseImagePathNotBetween(String value1, String value2) {
            addCriterion("use_image_path not between", value1, value2, "useImagePath");
            return (Criteria) this;
        }

        public Criteria andTotalNoIsNull() {
            addCriterion("total_no is null");
            return (Criteria) this;
        }

        public Criteria andTotalNoIsNotNull() {
            addCriterion("total_no is not null");
            return (Criteria) this;
        }

        public Criteria andTotalNoEqualTo(Integer value) {
            addCriterion("total_no =", value, "totalNo");
            return (Criteria) this;
        }

        public Criteria andTotalNoNotEqualTo(Integer value) {
            addCriterion("total_no <>", value, "totalNo");
            return (Criteria) this;
        }

        public Criteria andTotalNoGreaterThan(Integer value) {
            addCriterion("total_no >", value, "totalNo");
            return (Criteria) this;
        }

        public Criteria andTotalNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("total_no >=", value, "totalNo");
            return (Criteria) this;
        }

        public Criteria andTotalNoLessThan(Integer value) {
            addCriterion("total_no <", value, "totalNo");
            return (Criteria) this;
        }

        public Criteria andTotalNoLessThanOrEqualTo(Integer value) {
            addCriterion("total_no <=", value, "totalNo");
            return (Criteria) this;
        }

        public Criteria andTotalNoIn(List<Integer> values) {
            addCriterion("total_no in", values, "totalNo");
            return (Criteria) this;
        }

        public Criteria andTotalNoNotIn(List<Integer> values) {
            addCriterion("total_no not in", values, "totalNo");
            return (Criteria) this;
        }

        public Criteria andTotalNoBetween(Integer value1, Integer value2) {
            addCriterion("total_no between", value1, value2, "totalNo");
            return (Criteria) this;
        }

        public Criteria andTotalNoNotBetween(Integer value1, Integer value2) {
            addCriterion("total_no not between", value1, value2, "totalNo");
            return (Criteria) this;
        }

        public Criteria andCouponNoPerCustIsNull() {
            addCriterion("coupon_no_per_cust is null");
            return (Criteria) this;
        }

        public Criteria andCouponNoPerCustIsNotNull() {
            addCriterion("coupon_no_per_cust is not null");
            return (Criteria) this;
        }

        public Criteria andCouponNoPerCustEqualTo(Integer value) {
            addCriterion("coupon_no_per_cust =", value, "couponNoPerCust");
            return (Criteria) this;
        }

        public Criteria andCouponNoPerCustNotEqualTo(Integer value) {
            addCriterion("coupon_no_per_cust <>", value, "couponNoPerCust");
            return (Criteria) this;
        }

        public Criteria andCouponNoPerCustGreaterThan(Integer value) {
            addCriterion("coupon_no_per_cust >", value, "couponNoPerCust");
            return (Criteria) this;
        }

        public Criteria andCouponNoPerCustGreaterThanOrEqualTo(Integer value) {
            addCriterion("coupon_no_per_cust >=", value, "couponNoPerCust");
            return (Criteria) this;
        }

        public Criteria andCouponNoPerCustLessThan(Integer value) {
            addCriterion("coupon_no_per_cust <", value, "couponNoPerCust");
            return (Criteria) this;
        }

        public Criteria andCouponNoPerCustLessThanOrEqualTo(Integer value) {
            addCriterion("coupon_no_per_cust <=", value, "couponNoPerCust");
            return (Criteria) this;
        }

        public Criteria andCouponNoPerCustIn(List<Integer> values) {
            addCriterion("coupon_no_per_cust in", values, "couponNoPerCust");
            return (Criteria) this;
        }

        public Criteria andCouponNoPerCustNotIn(List<Integer> values) {
            addCriterion("coupon_no_per_cust not in", values, "couponNoPerCust");
            return (Criteria) this;
        }

        public Criteria andCouponNoPerCustBetween(Integer value1, Integer value2) {
            addCriterion("coupon_no_per_cust between", value1, value2, "couponNoPerCust");
            return (Criteria) this;
        }

        public Criteria andCouponNoPerCustNotBetween(Integer value1, Integer value2) {
            addCriterion("coupon_no_per_cust not between", value1, value2, "couponNoPerCust");
            return (Criteria) this;
        }

        public Criteria andSpecialEventMmIsNull() {
            addCriterion("special_event_mm is null");
            return (Criteria) this;
        }

        public Criteria andSpecialEventMmIsNotNull() {
            addCriterion("special_event_mm is not null");
            return (Criteria) this;
        }

        public Criteria andSpecialEventMmEqualTo(String value) {
            addCriterion("special_event_mm =", value, "specialEventMm");
            return (Criteria) this;
        }

        public Criteria andSpecialEventMmNotEqualTo(String value) {
            addCriterion("special_event_mm <>", value, "specialEventMm");
            return (Criteria) this;
        }

        public Criteria andSpecialEventMmGreaterThan(String value) {
            addCriterion("special_event_mm >", value, "specialEventMm");
            return (Criteria) this;
        }

        public Criteria andSpecialEventMmGreaterThanOrEqualTo(String value) {
            addCriterion("special_event_mm >=", value, "specialEventMm");
            return (Criteria) this;
        }

        public Criteria andSpecialEventMmLessThan(String value) {
            addCriterion("special_event_mm <", value, "specialEventMm");
            return (Criteria) this;
        }

        public Criteria andSpecialEventMmLessThanOrEqualTo(String value) {
            addCriterion("special_event_mm <=", value, "specialEventMm");
            return (Criteria) this;
        }

        public Criteria andSpecialEventMmLike(String value) {
            addCriterion("special_event_mm like", value, "specialEventMm");
            return (Criteria) this;
        }

        public Criteria andSpecialEventMmNotLike(String value) {
            addCriterion("special_event_mm not like", value, "specialEventMm");
            return (Criteria) this;
        }

        public Criteria andSpecialEventMmIn(List<String> values) {
            addCriterion("special_event_mm in", values, "specialEventMm");
            return (Criteria) this;
        }

        public Criteria andSpecialEventMmNotIn(List<String> values) {
            addCriterion("special_event_mm not in", values, "specialEventMm");
            return (Criteria) this;
        }

        public Criteria andSpecialEventMmBetween(String value1, String value2) {
            addCriterion("special_event_mm between", value1, value2, "specialEventMm");
            return (Criteria) this;
        }

        public Criteria andSpecialEventMmNotBetween(String value1, String value2) {
            addCriterion("special_event_mm not between", value1, value2, "specialEventMm");
            return (Criteria) this;
        }

        public Criteria andSpecialEventEnIsNull() {
            addCriterion("special_event_en is null");
            return (Criteria) this;
        }

        public Criteria andSpecialEventEnIsNotNull() {
            addCriterion("special_event_en is not null");
            return (Criteria) this;
        }

        public Criteria andSpecialEventEnEqualTo(String value) {
            addCriterion("special_event_en =", value, "specialEventEn");
            return (Criteria) this;
        }

        public Criteria andSpecialEventEnNotEqualTo(String value) {
            addCriterion("special_event_en <>", value, "specialEventEn");
            return (Criteria) this;
        }

        public Criteria andSpecialEventEnGreaterThan(String value) {
            addCriterion("special_event_en >", value, "specialEventEn");
            return (Criteria) this;
        }

        public Criteria andSpecialEventEnGreaterThanOrEqualTo(String value) {
            addCriterion("special_event_en >=", value, "specialEventEn");
            return (Criteria) this;
        }

        public Criteria andSpecialEventEnLessThan(String value) {
            addCriterion("special_event_en <", value, "specialEventEn");
            return (Criteria) this;
        }

        public Criteria andSpecialEventEnLessThanOrEqualTo(String value) {
            addCriterion("special_event_en <=", value, "specialEventEn");
            return (Criteria) this;
        }

        public Criteria andSpecialEventEnLike(String value) {
            addCriterion("special_event_en like", value, "specialEventEn");
            return (Criteria) this;
        }

        public Criteria andSpecialEventEnNotLike(String value) {
            addCriterion("special_event_en not like", value, "specialEventEn");
            return (Criteria) this;
        }

        public Criteria andSpecialEventEnIn(List<String> values) {
            addCriterion("special_event_en in", values, "specialEventEn");
            return (Criteria) this;
        }

        public Criteria andSpecialEventEnNotIn(List<String> values) {
            addCriterion("special_event_en not in", values, "specialEventEn");
            return (Criteria) this;
        }

        public Criteria andSpecialEventEnBetween(String value1, String value2) {
            addCriterion("special_event_en between", value1, value2, "specialEventEn");
            return (Criteria) this;
        }

        public Criteria andSpecialEventEnNotBetween(String value1, String value2) {
            addCriterion("special_event_en not between", value1, value2, "specialEventEn");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(Short value) {
            addCriterion("del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(Short value) {
            addCriterion("del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(Short value) {
            addCriterion("del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(Short value) {
            addCriterion("del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(Short value) {
            addCriterion("del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(Short value) {
            addCriterion("del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<Short> values) {
            addCriterion("del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<Short> values) {
            addCriterion("del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(Short value1, Short value2) {
            addCriterion("del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(Short value1, Short value2) {
            addCriterion("del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("created_by like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("created_by not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNull() {
            addCriterion("updated_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNotNull() {
            addCriterion("updated_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByEqualTo(String value) {
            addCriterion("updated_by =", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotEqualTo(String value) {
            addCriterion("updated_by <>", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThan(String value) {
            addCriterion("updated_by >", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThanOrEqualTo(String value) {
            addCriterion("updated_by >=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThan(String value) {
            addCriterion("updated_by <", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThanOrEqualTo(String value) {
            addCriterion("updated_by <=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLike(String value) {
            addCriterion("updated_by like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotLike(String value) {
            addCriterion("updated_by not like", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIn(List<String> values) {
            addCriterion("updated_by in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotIn(List<String> values) {
            addCriterion("updated_by not in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByBetween(String value1, String value2) {
            addCriterion("updated_by between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotBetween(String value1, String value2) {
            addCriterion("updated_by not between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNull() {
            addCriterion("created_time is null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIsNotNull() {
            addCriterion("created_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeEqualTo(Date value) {
            addCriterion("created_time =", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotEqualTo(Date value) {
            addCriterion("created_time <>", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThan(Date value) {
            addCriterion("created_time >", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("created_time >=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThan(Date value) {
            addCriterion("created_time <", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("created_time <=", value, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeIn(List<Date> values) {
            addCriterion("created_time in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotIn(List<Date> values) {
            addCriterion("created_time not in", values, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeBetween(Date value1, Date value2) {
            addCriterion("created_time between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andCreatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("created_time not between", value1, value2, "createdTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNull() {
            addCriterion("updated_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIsNotNull() {
            addCriterion("updated_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeEqualTo(Date value) {
            addCriterion("updated_time =", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotEqualTo(Date value) {
            addCriterion("updated_time <>", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThan(Date value) {
            addCriterion("updated_time >", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_time >=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThan(Date value) {
            addCriterion("updated_time <", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeLessThanOrEqualTo(Date value) {
            addCriterion("updated_time <=", value, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeIn(List<Date> values) {
            addCriterion("updated_time in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotIn(List<Date> values) {
            addCriterion("updated_time not in", values, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeBetween(Date value1, Date value2) {
            addCriterion("updated_time between", value1, value2, "updatedTime");
            return (Criteria) this;
        }

        public Criteria andUpdatedTimeNotBetween(Date value1, Date value2) {
            addCriterion("updated_time not between", value1, value2, "updatedTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vcs.coupon_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table vcs.coupon_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}