package mm.aeon.com.zgen.entity;

import java.util.Date;

public class CustRoomInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.cust_room_info.cust_room_id
     *
     * @mbg.generated
     */
    private Integer custRoomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.cust_room_info.customer_id
     *
     * @mbg.generated
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.cust_room_info.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.cust_room_info.last_send_time
     *
     * @mbg.generated
     */
    private Date lastSendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.cust_room_info.conver_lock_flag
     *
     * @mbg.generated
     */
    private Short converLockFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.cust_room_info.cust_room_id
     *
     * @return the value of vcs.cust_room_info.cust_room_id
     *
     * @mbg.generated
     */
    public Integer getCustRoomId() {
        return custRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.cust_room_info.cust_room_id
     *
     * @param custRoomId the value for vcs.cust_room_info.cust_room_id
     *
     * @mbg.generated
     */
    public void setCustRoomId(Integer custRoomId) {
        this.custRoomId = custRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.cust_room_info.customer_id
     *
     * @return the value of vcs.cust_room_info.customer_id
     *
     * @mbg.generated
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.cust_room_info.customer_id
     *
     * @param customerId the value for vcs.cust_room_info.customer_id
     *
     * @mbg.generated
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.cust_room_info.created_time
     *
     * @return the value of vcs.cust_room_info.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.cust_room_info.created_time
     *
     * @param createdTime the value for vcs.cust_room_info.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.cust_room_info.last_send_time
     *
     * @return the value of vcs.cust_room_info.last_send_time
     *
     * @mbg.generated
     */
    public Date getLastSendTime() {
        return lastSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.cust_room_info.last_send_time
     *
     * @param lastSendTime the value for vcs.cust_room_info.last_send_time
     *
     * @mbg.generated
     */
    public void setLastSendTime(Date lastSendTime) {
        this.lastSendTime = lastSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.cust_room_info.conver_lock_flag
     *
     * @return the value of vcs.cust_room_info.conver_lock_flag
     *
     * @mbg.generated
     */
    public Short getConverLockFlag() {
        return converLockFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.cust_room_info.conver_lock_flag
     *
     * @param converLockFlag the value for vcs.cust_room_info.conver_lock_flag
     *
     * @mbg.generated
     */
    public void setConverLockFlag(Short converLockFlag) {
        this.converLockFlag = converLockFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.cust_room_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", custRoomId=").append(custRoomId);
        sb.append(", customerId=").append(customerId);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", lastSendTime=").append(lastSendTime);
        sb.append(", converLockFlag=").append(converLockFlag);
        sb.append("]");
        return sb.toString();
    }
}