package mm.aeon.com.zgen.entity;

import java.math.BigDecimal;
import java.util.Date;

public class DaPurchaseInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.da_purchase_info.da_purchase_info_id
     *
     * @mbg.generated
     */
    private Integer daPurchaseInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.da_purchase_info.da_application_info_id
     *
     * @mbg.generated
     */
    private Integer daApplicationInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.da_purchase_info.agreement_no
     *
     * @mbg.generated
     */
    private String agreementNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.da_purchase_info.purchase_date
     *
     * @mbg.generated
     */
    private Date purchaseDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.da_purchase_info.outlet_id
     *
     * @mbg.generated
     */
    private Integer outletId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.da_purchase_info.outlet_name
     *
     * @mbg.generated
     */
    private String outletName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.da_purchase_info.invoice_no
     *
     * @mbg.generated
     */
    private String invoiceNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.da_purchase_info.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.da_purchase_info.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.da_purchase_info.updated_time
     *
     * @mbg.generated
     */
    private Date updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.da_purchase_info.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.da_purchase_info.del_flag
     *
     * @mbg.generated
     */
    private Boolean delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.da_purchase_info.agent_id
     *
     * @mbg.generated
     */
    private Integer agentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.da_purchase_info.agent_name
     *
     * @mbg.generated
     */
    private String agentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.da_purchase_info.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.da_purchase_info.settlement_amount
     *
     * @mbg.generated
     */
    private BigDecimal settlementAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.da_purchase_info.purchase_location
     *
     * @mbg.generated
     */
    private String purchaseLocation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.da_purchase_info.da_purchase_info_id
     *
     * @return the value of vcs.da_purchase_info.da_purchase_info_id
     *
     * @mbg.generated
     */
    public Integer getDaPurchaseInfoId() {
        return daPurchaseInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.da_purchase_info.da_purchase_info_id
     *
     * @param daPurchaseInfoId the value for vcs.da_purchase_info.da_purchase_info_id
     *
     * @mbg.generated
     */
    public void setDaPurchaseInfoId(Integer daPurchaseInfoId) {
        this.daPurchaseInfoId = daPurchaseInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.da_purchase_info.da_application_info_id
     *
     * @return the value of vcs.da_purchase_info.da_application_info_id
     *
     * @mbg.generated
     */
    public Integer getDaApplicationInfoId() {
        return daApplicationInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.da_purchase_info.da_application_info_id
     *
     * @param daApplicationInfoId the value for vcs.da_purchase_info.da_application_info_id
     *
     * @mbg.generated
     */
    public void setDaApplicationInfoId(Integer daApplicationInfoId) {
        this.daApplicationInfoId = daApplicationInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.da_purchase_info.agreement_no
     *
     * @return the value of vcs.da_purchase_info.agreement_no
     *
     * @mbg.generated
     */
    public String getAgreementNo() {
        return agreementNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.da_purchase_info.agreement_no
     *
     * @param agreementNo the value for vcs.da_purchase_info.agreement_no
     *
     * @mbg.generated
     */
    public void setAgreementNo(String agreementNo) {
        this.agreementNo = agreementNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.da_purchase_info.purchase_date
     *
     * @return the value of vcs.da_purchase_info.purchase_date
     *
     * @mbg.generated
     */
    public Date getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.da_purchase_info.purchase_date
     *
     * @param purchaseDate the value for vcs.da_purchase_info.purchase_date
     *
     * @mbg.generated
     */
    public void setPurchaseDate(Date purchaseDate) {
        this.purchaseDate = purchaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.da_purchase_info.outlet_id
     *
     * @return the value of vcs.da_purchase_info.outlet_id
     *
     * @mbg.generated
     */
    public Integer getOutletId() {
        return outletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.da_purchase_info.outlet_id
     *
     * @param outletId the value for vcs.da_purchase_info.outlet_id
     *
     * @mbg.generated
     */
    public void setOutletId(Integer outletId) {
        this.outletId = outletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.da_purchase_info.outlet_name
     *
     * @return the value of vcs.da_purchase_info.outlet_name
     *
     * @mbg.generated
     */
    public String getOutletName() {
        return outletName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.da_purchase_info.outlet_name
     *
     * @param outletName the value for vcs.da_purchase_info.outlet_name
     *
     * @mbg.generated
     */
    public void setOutletName(String outletName) {
        this.outletName = outletName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.da_purchase_info.invoice_no
     *
     * @return the value of vcs.da_purchase_info.invoice_no
     *
     * @mbg.generated
     */
    public String getInvoiceNo() {
        return invoiceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.da_purchase_info.invoice_no
     *
     * @param invoiceNo the value for vcs.da_purchase_info.invoice_no
     *
     * @mbg.generated
     */
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.da_purchase_info.created_time
     *
     * @return the value of vcs.da_purchase_info.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.da_purchase_info.created_time
     *
     * @param createdTime the value for vcs.da_purchase_info.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.da_purchase_info.created_by
     *
     * @return the value of vcs.da_purchase_info.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.da_purchase_info.created_by
     *
     * @param createdBy the value for vcs.da_purchase_info.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.da_purchase_info.updated_time
     *
     * @return the value of vcs.da_purchase_info.updated_time
     *
     * @mbg.generated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.da_purchase_info.updated_time
     *
     * @param updatedTime the value for vcs.da_purchase_info.updated_time
     *
     * @mbg.generated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.da_purchase_info.updated_by
     *
     * @return the value of vcs.da_purchase_info.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.da_purchase_info.updated_by
     *
     * @param updatedBy the value for vcs.da_purchase_info.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.da_purchase_info.del_flag
     *
     * @return the value of vcs.da_purchase_info.del_flag
     *
     * @mbg.generated
     */
    public Boolean getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.da_purchase_info.del_flag
     *
     * @param delFlag the value for vcs.da_purchase_info.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Boolean delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.da_purchase_info.agent_id
     *
     * @return the value of vcs.da_purchase_info.agent_id
     *
     * @mbg.generated
     */
    public Integer getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.da_purchase_info.agent_id
     *
     * @param agentId the value for vcs.da_purchase_info.agent_id
     *
     * @mbg.generated
     */
    public void setAgentId(Integer agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.da_purchase_info.agent_name
     *
     * @return the value of vcs.da_purchase_info.agent_name
     *
     * @mbg.generated
     */
    public String getAgentName() {
        return agentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.da_purchase_info.agent_name
     *
     * @param agentName the value for vcs.da_purchase_info.agent_name
     *
     * @mbg.generated
     */
    public void setAgentName(String agentName) {
        this.agentName = agentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.da_purchase_info.status
     *
     * @return the value of vcs.da_purchase_info.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.da_purchase_info.status
     *
     * @param status the value for vcs.da_purchase_info.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.da_purchase_info.settlement_amount
     *
     * @return the value of vcs.da_purchase_info.settlement_amount
     *
     * @mbg.generated
     */
    public BigDecimal getSettlementAmount() {
        return settlementAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.da_purchase_info.settlement_amount
     *
     * @param settlementAmount the value for vcs.da_purchase_info.settlement_amount
     *
     * @mbg.generated
     */
    public void setSettlementAmount(BigDecimal settlementAmount) {
        this.settlementAmount = settlementAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.da_purchase_info.purchase_location
     *
     * @return the value of vcs.da_purchase_info.purchase_location
     *
     * @mbg.generated
     */
    public String getPurchaseLocation() {
        return purchaseLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.da_purchase_info.purchase_location
     *
     * @param purchaseLocation the value for vcs.da_purchase_info.purchase_location
     *
     * @mbg.generated
     */
    public void setPurchaseLocation(String purchaseLocation) {
        this.purchaseLocation = purchaseLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.da_purchase_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", daPurchaseInfoId=").append(daPurchaseInfoId);
        sb.append(", daApplicationInfoId=").append(daApplicationInfoId);
        sb.append(", agreementNo=").append(agreementNo);
        sb.append(", purchaseDate=").append(purchaseDate);
        sb.append(", outletId=").append(outletId);
        sb.append(", outletName=").append(outletName);
        sb.append(", invoiceNo=").append(invoiceNo);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", agentId=").append(agentId);
        sb.append(", agentName=").append(agentName);
        sb.append(", status=").append(status);
        sb.append(", settlementAmount=").append(settlementAmount);
        sb.append(", purchaseLocation=").append(purchaseLocation);
        sb.append("]");
        return sb.toString();
    }
}