package mm.aeon.com.zgen.entity;

import java.util.Date;

public class FaqCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.faq_category.category_id
     *
     * @mbg.generated
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.faq_category.category
     *
     * @mbg.generated
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.faq_category.del_flag
     *
     * @mbg.generated
     */
    private Short delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.faq_category.category_myn
     *
     * @mbg.generated
     */
    private String categoryMyn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.faq_category.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.faq_category.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.faq_category.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.faq_category.updated_time
     *
     * @mbg.generated
     */
    private Date updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.faq_category.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.faq_category.category_id
     *
     * @return the value of vcs.faq_category.category_id
     *
     * @mbg.generated
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.faq_category.category_id
     *
     * @param categoryId the value for vcs.faq_category.category_id
     *
     * @mbg.generated
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.faq_category.category
     *
     * @return the value of vcs.faq_category.category
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.faq_category.category
     *
     * @param category the value for vcs.faq_category.category
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.faq_category.del_flag
     *
     * @return the value of vcs.faq_category.del_flag
     *
     * @mbg.generated
     */
    public Short getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.faq_category.del_flag
     *
     * @param delFlag the value for vcs.faq_category.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Short delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.faq_category.category_myn
     *
     * @return the value of vcs.faq_category.category_myn
     *
     * @mbg.generated
     */
    public String getCategoryMyn() {
        return categoryMyn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.faq_category.category_myn
     *
     * @param categoryMyn the value for vcs.faq_category.category_myn
     *
     * @mbg.generated
     */
    public void setCategoryMyn(String categoryMyn) {
        this.categoryMyn = categoryMyn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.faq_category.description
     *
     * @return the value of vcs.faq_category.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.faq_category.description
     *
     * @param description the value for vcs.faq_category.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.faq_category.created_time
     *
     * @return the value of vcs.faq_category.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.faq_category.created_time
     *
     * @param createdTime the value for vcs.faq_category.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.faq_category.created_by
     *
     * @return the value of vcs.faq_category.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.faq_category.created_by
     *
     * @param createdBy the value for vcs.faq_category.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.faq_category.updated_time
     *
     * @return the value of vcs.faq_category.updated_time
     *
     * @mbg.generated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.faq_category.updated_time
     *
     * @param updatedTime the value for vcs.faq_category.updated_time
     *
     * @mbg.generated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.faq_category.updated_by
     *
     * @return the value of vcs.faq_category.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.faq_category.updated_by
     *
     * @param updatedBy the value for vcs.faq_category.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.faq_category
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", categoryId=").append(categoryId);
        sb.append(", category=").append(category);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", categoryMyn=").append(categoryMyn);
        sb.append(", description=").append(description);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append("]");
        return sb.toString();
    }
}