package mm.aeon.com.zgen.entity;

import java.util.Date;

public class FreeCustRoomInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.free_cust_room_info.free_cust_room_info_id
     *
     * @mbg.generated
     */
    private Integer freeCustRoomInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.free_cust_room_info.free_customer_info_id
     *
     * @mbg.generated
     */
    private Integer freeCustomerInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.free_cust_room_info.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.free_cust_room_info.last_send_time
     *
     * @mbg.generated
     */
    private Date lastSendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.free_cust_room_info.conver_lock_flag
     *
     * @mbg.generated
     */
    private Short converLockFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.free_cust_room_info.free_cust_room_info_id
     *
     * @return the value of vcs.free_cust_room_info.free_cust_room_info_id
     *
     * @mbg.generated
     */
    public Integer getFreeCustRoomInfoId() {
        return freeCustRoomInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.free_cust_room_info.free_cust_room_info_id
     *
     * @param freeCustRoomInfoId the value for vcs.free_cust_room_info.free_cust_room_info_id
     *
     * @mbg.generated
     */
    public void setFreeCustRoomInfoId(Integer freeCustRoomInfoId) {
        this.freeCustRoomInfoId = freeCustRoomInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.free_cust_room_info.free_customer_info_id
     *
     * @return the value of vcs.free_cust_room_info.free_customer_info_id
     *
     * @mbg.generated
     */
    public Integer getFreeCustomerInfoId() {
        return freeCustomerInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.free_cust_room_info.free_customer_info_id
     *
     * @param freeCustomerInfoId the value for vcs.free_cust_room_info.free_customer_info_id
     *
     * @mbg.generated
     */
    public void setFreeCustomerInfoId(Integer freeCustomerInfoId) {
        this.freeCustomerInfoId = freeCustomerInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.free_cust_room_info.created_time
     *
     * @return the value of vcs.free_cust_room_info.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.free_cust_room_info.created_time
     *
     * @param createdTime the value for vcs.free_cust_room_info.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.free_cust_room_info.last_send_time
     *
     * @return the value of vcs.free_cust_room_info.last_send_time
     *
     * @mbg.generated
     */
    public Date getLastSendTime() {
        return lastSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.free_cust_room_info.last_send_time
     *
     * @param lastSendTime the value for vcs.free_cust_room_info.last_send_time
     *
     * @mbg.generated
     */
    public void setLastSendTime(Date lastSendTime) {
        this.lastSendTime = lastSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.free_cust_room_info.conver_lock_flag
     *
     * @return the value of vcs.free_cust_room_info.conver_lock_flag
     *
     * @mbg.generated
     */
    public Short getConverLockFlag() {
        return converLockFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.free_cust_room_info.conver_lock_flag
     *
     * @param converLockFlag the value for vcs.free_cust_room_info.conver_lock_flag
     *
     * @mbg.generated
     */
    public void setConverLockFlag(Short converLockFlag) {
        this.converLockFlag = converLockFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.free_cust_room_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", freeCustRoomInfoId=").append(freeCustRoomInfoId);
        sb.append(", freeCustomerInfoId=").append(freeCustomerInfoId);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", lastSendTime=").append(lastSendTime);
        sb.append(", converLockFlag=").append(converLockFlag);
        sb.append("]");
        return sb.toString();
    }
}