package mm.aeon.com.zgen.entity;

import java.util.Date;

public class MainMenu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.main_menu.main_menu_id
     *
     * @mbg.generated
     */
    private Integer mainMenuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.main_menu.menu_name
     *
     * @mbg.generated
     */
    private String menuName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.main_menu.menu_action
     *
     * @mbg.generated
     */
    private String menuAction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.main_menu.menu_display_order
     *
     * @mbg.generated
     */
    private Integer menuDisplayOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.main_menu.del_flag
     *
     * @mbg.generated
     */
    private Short delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.main_menu.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.main_menu.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.main_menu.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.main_menu.updated_time
     *
     * @mbg.generated
     */
    private Object updatedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.main_menu.system_flag
     *
     * @mbg.generated
     */
    private String systemFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.main_menu.main_menu_id
     *
     * @return the value of vcs.main_menu.main_menu_id
     *
     * @mbg.generated
     */
    public Integer getMainMenuId() {
        return mainMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.main_menu.main_menu_id
     *
     * @param mainMenuId the value for vcs.main_menu.main_menu_id
     *
     * @mbg.generated
     */
    public void setMainMenuId(Integer mainMenuId) {
        this.mainMenuId = mainMenuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.main_menu.menu_name
     *
     * @return the value of vcs.main_menu.menu_name
     *
     * @mbg.generated
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.main_menu.menu_name
     *
     * @param menuName the value for vcs.main_menu.menu_name
     *
     * @mbg.generated
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.main_menu.menu_action
     *
     * @return the value of vcs.main_menu.menu_action
     *
     * @mbg.generated
     */
    public String getMenuAction() {
        return menuAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.main_menu.menu_action
     *
     * @param menuAction the value for vcs.main_menu.menu_action
     *
     * @mbg.generated
     */
    public void setMenuAction(String menuAction) {
        this.menuAction = menuAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.main_menu.menu_display_order
     *
     * @return the value of vcs.main_menu.menu_display_order
     *
     * @mbg.generated
     */
    public Integer getMenuDisplayOrder() {
        return menuDisplayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.main_menu.menu_display_order
     *
     * @param menuDisplayOrder the value for vcs.main_menu.menu_display_order
     *
     * @mbg.generated
     */
    public void setMenuDisplayOrder(Integer menuDisplayOrder) {
        this.menuDisplayOrder = menuDisplayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.main_menu.del_flag
     *
     * @return the value of vcs.main_menu.del_flag
     *
     * @mbg.generated
     */
    public Short getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.main_menu.del_flag
     *
     * @param delFlag the value for vcs.main_menu.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Short delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.main_menu.created_by
     *
     * @return the value of vcs.main_menu.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.main_menu.created_by
     *
     * @param createdBy the value for vcs.main_menu.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.main_menu.created_time
     *
     * @return the value of vcs.main_menu.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.main_menu.created_time
     *
     * @param createdTime the value for vcs.main_menu.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.main_menu.updated_by
     *
     * @return the value of vcs.main_menu.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.main_menu.updated_by
     *
     * @param updatedBy the value for vcs.main_menu.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.main_menu.updated_time
     *
     * @return the value of vcs.main_menu.updated_time
     *
     * @mbg.generated
     */
    public Object getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.main_menu.updated_time
     *
     * @param updatedTime the value for vcs.main_menu.updated_time
     *
     * @mbg.generated
     */
    public void setUpdatedTime(Object updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.main_menu.system_flag
     *
     * @return the value of vcs.main_menu.system_flag
     *
     * @mbg.generated
     */
    public String getSystemFlag() {
        return systemFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.main_menu.system_flag
     *
     * @param systemFlag the value for vcs.main_menu.system_flag
     *
     * @mbg.generated
     */
    public void setSystemFlag(String systemFlag) {
        this.systemFlag = systemFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.main_menu
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", mainMenuId=").append(mainMenuId);
        sb.append(", menuName=").append(menuName);
        sb.append(", menuAction=").append(menuAction);
        sb.append(", menuDisplayOrder=").append(menuDisplayOrder);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append(", systemFlag=").append(systemFlag);
        sb.append("]");
        return sb.toString();
    }
}