package mm.aeon.com.zgen.entity;

import java.util.Date;

public class PlAdminCustRoom {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.pl_admin_cust_room.pl_ad_cust_room_id
     *
     * @mbg.generated
     */
    private Integer plAdCustRoomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.pl_admin_cust_room.pl_cust_room_id
     *
     * @mbg.generated
     */
    private Integer plCustRoomId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.pl_admin_cust_room.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.pl_admin_cust_room.finish_flag
     *
     * @mbg.generated
     */
    private Short finishFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.pl_admin_cust_room.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.pl_admin_cust_room.pl_ad_cust_room_id
     *
     * @return the value of vcs.pl_admin_cust_room.pl_ad_cust_room_id
     *
     * @mbg.generated
     */
    public Integer getPlAdCustRoomId() {
        return plAdCustRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.pl_admin_cust_room.pl_ad_cust_room_id
     *
     * @param plAdCustRoomId the value for vcs.pl_admin_cust_room.pl_ad_cust_room_id
     *
     * @mbg.generated
     */
    public void setPlAdCustRoomId(Integer plAdCustRoomId) {
        this.plAdCustRoomId = plAdCustRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.pl_admin_cust_room.pl_cust_room_id
     *
     * @return the value of vcs.pl_admin_cust_room.pl_cust_room_id
     *
     * @mbg.generated
     */
    public Integer getPlCustRoomId() {
        return plCustRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.pl_admin_cust_room.pl_cust_room_id
     *
     * @param plCustRoomId the value for vcs.pl_admin_cust_room.pl_cust_room_id
     *
     * @mbg.generated
     */
    public void setPlCustRoomId(Integer plCustRoomId) {
        this.plCustRoomId = plCustRoomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.pl_admin_cust_room.user_id
     *
     * @return the value of vcs.pl_admin_cust_room.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.pl_admin_cust_room.user_id
     *
     * @param userId the value for vcs.pl_admin_cust_room.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.pl_admin_cust_room.finish_flag
     *
     * @return the value of vcs.pl_admin_cust_room.finish_flag
     *
     * @mbg.generated
     */
    public Short getFinishFlag() {
        return finishFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.pl_admin_cust_room.finish_flag
     *
     * @param finishFlag the value for vcs.pl_admin_cust_room.finish_flag
     *
     * @mbg.generated
     */
    public void setFinishFlag(Short finishFlag) {
        this.finishFlag = finishFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.pl_admin_cust_room.created_time
     *
     * @return the value of vcs.pl_admin_cust_room.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.pl_admin_cust_room.created_time
     *
     * @param createdTime the value for vcs.pl_admin_cust_room.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.pl_admin_cust_room
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", plAdCustRoomId=").append(plAdCustRoomId);
        sb.append(", plCustRoomId=").append(plCustRoomId);
        sb.append(", userId=").append(userId);
        sb.append(", finishFlag=").append(finishFlag);
        sb.append(", createdTime=").append(createdTime);
        sb.append("]");
        return sb.toString();
    }
}