package mm.aeon.com.zgen.entity;

import java.util.Date;

public class SecurityQuestion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.security_question.sec_ques_id
     *
     * @mbg.generated
     */
    private Integer secQuesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.security_question.question_myan
     *
     * @mbg.generated
     */
    private String questionMyan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.security_question.question_eng
     *
     * @mbg.generated
     */
    private String questionEng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.security_question.del_flag
     *
     * @mbg.generated
     */
    private Short delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.security_question.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.security_question.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.security_question.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.security_question.updated_time
     *
     * @mbg.generated
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.security_question.sec_ques_id
     *
     * @return the value of vcs.security_question.sec_ques_id
     *
     * @mbg.generated
     */
    public Integer getSecQuesId() {
        return secQuesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.security_question.sec_ques_id
     *
     * @param secQuesId the value for vcs.security_question.sec_ques_id
     *
     * @mbg.generated
     */
    public void setSecQuesId(Integer secQuesId) {
        this.secQuesId = secQuesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.security_question.question_myan
     *
     * @return the value of vcs.security_question.question_myan
     *
     * @mbg.generated
     */
    public String getQuestionMyan() {
        return questionMyan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.security_question.question_myan
     *
     * @param questionMyan the value for vcs.security_question.question_myan
     *
     * @mbg.generated
     */
    public void setQuestionMyan(String questionMyan) {
        this.questionMyan = questionMyan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.security_question.question_eng
     *
     * @return the value of vcs.security_question.question_eng
     *
     * @mbg.generated
     */
    public String getQuestionEng() {
        return questionEng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.security_question.question_eng
     *
     * @param questionEng the value for vcs.security_question.question_eng
     *
     * @mbg.generated
     */
    public void setQuestionEng(String questionEng) {
        this.questionEng = questionEng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.security_question.del_flag
     *
     * @return the value of vcs.security_question.del_flag
     *
     * @mbg.generated
     */
    public Short getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.security_question.del_flag
     *
     * @param delFlag the value for vcs.security_question.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Short delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.security_question.created_by
     *
     * @return the value of vcs.security_question.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.security_question.created_by
     *
     * @param createdBy the value for vcs.security_question.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.security_question.updated_by
     *
     * @return the value of vcs.security_question.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.security_question.updated_by
     *
     * @param updatedBy the value for vcs.security_question.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.security_question.created_time
     *
     * @return the value of vcs.security_question.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.security_question.created_time
     *
     * @param createdTime the value for vcs.security_question.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.security_question.updated_time
     *
     * @return the value of vcs.security_question.updated_time
     *
     * @mbg.generated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.security_question.updated_time
     *
     * @param updatedTime the value for vcs.security_question.updated_time
     *
     * @mbg.generated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.security_question
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", secQuesId=").append(secQuesId);
        sb.append(", questionMyan=").append(questionMyan);
        sb.append(", questionEng=").append(questionEng);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append("]");
        return sb.toString();
    }
}