package mm.aeon.com.zgen.entity;

import java.util.Date;

public class ShopInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.shop_info.shop_id
     *
     * @mbg.generated
     */
    private Integer shopId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.shop_info.shop_name
     *
     * @mbg.generated
     */
    private String shopName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.shop_info.shop_code
     *
     * @mbg.generated
     */
    private String shopCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.shop_info.coupon_code
     *
     * @mbg.generated
     */
    private String couponCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.shop_info.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.shop_info.del_flag
     *
     * @mbg.generated
     */
    private Short delFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.shop_info.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.shop_info.updated_by
     *
     * @mbg.generated
     */
    private String updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.shop_info.created_time
     *
     * @mbg.generated
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vcs.shop_info.updated_time
     *
     * @mbg.generated
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.shop_info.shop_id
     *
     * @return the value of vcs.shop_info.shop_id
     *
     * @mbg.generated
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.shop_info.shop_id
     *
     * @param shopId the value for vcs.shop_info.shop_id
     *
     * @mbg.generated
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.shop_info.shop_name
     *
     * @return the value of vcs.shop_info.shop_name
     *
     * @mbg.generated
     */
    public String getShopName() {
        return shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.shop_info.shop_name
     *
     * @param shopName the value for vcs.shop_info.shop_name
     *
     * @mbg.generated
     */
    public void setShopName(String shopName) {
        this.shopName = shopName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.shop_info.shop_code
     *
     * @return the value of vcs.shop_info.shop_code
     *
     * @mbg.generated
     */
    public String getShopCode() {
        return shopCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.shop_info.shop_code
     *
     * @param shopCode the value for vcs.shop_info.shop_code
     *
     * @mbg.generated
     */
    public void setShopCode(String shopCode) {
        this.shopCode = shopCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.shop_info.coupon_code
     *
     * @return the value of vcs.shop_info.coupon_code
     *
     * @mbg.generated
     */
    public String getCouponCode() {
        return couponCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.shop_info.coupon_code
     *
     * @param couponCode the value for vcs.shop_info.coupon_code
     *
     * @mbg.generated
     */
    public void setCouponCode(String couponCode) {
        this.couponCode = couponCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.shop_info.address
     *
     * @return the value of vcs.shop_info.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.shop_info.address
     *
     * @param address the value for vcs.shop_info.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.shop_info.del_flag
     *
     * @return the value of vcs.shop_info.del_flag
     *
     * @mbg.generated
     */
    public Short getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.shop_info.del_flag
     *
     * @param delFlag the value for vcs.shop_info.del_flag
     *
     * @mbg.generated
     */
    public void setDelFlag(Short delFlag) {
        this.delFlag = delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.shop_info.created_by
     *
     * @return the value of vcs.shop_info.created_by
     *
     * @mbg.generated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.shop_info.created_by
     *
     * @param createdBy the value for vcs.shop_info.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.shop_info.updated_by
     *
     * @return the value of vcs.shop_info.updated_by
     *
     * @mbg.generated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.shop_info.updated_by
     *
     * @param updatedBy the value for vcs.shop_info.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.shop_info.created_time
     *
     * @return the value of vcs.shop_info.created_time
     *
     * @mbg.generated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.shop_info.created_time
     *
     * @param createdTime the value for vcs.shop_info.created_time
     *
     * @mbg.generated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vcs.shop_info.updated_time
     *
     * @return the value of vcs.shop_info.updated_time
     *
     * @mbg.generated
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vcs.shop_info.updated_time
     *
     * @param updatedTime the value for vcs.shop_info.updated_time
     *
     * @mbg.generated
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vcs.shop_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", shopId=").append(shopId);
        sb.append(", shopName=").append(shopName);
        sb.append(", shopCode=").append(shopCode);
        sb.append(", couponCode=").append(couponCode);
        sb.append(", address=").append(address);
        sb.append(", delFlag=").append(delFlag);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", createdTime=").append(createdTime);
        sb.append(", updatedTime=").append(updatedTime);
        sb.append("]");
        return sb.toString();
    }
}